# CNN-EXP-037 — Frozen WIDTH64 Hard-FP Reranker

## Гипотеза

Проверяем только **objective + hard-negative sampling**.

```text
Frozen WIDTH64 backbone
RF = 1029
        ↓
64-D feature / nucleotide
        ↓
Linear presence head
64 → 1
```

Не добавляем MLP, не меняем backbone, не переходим на WIDTH128.

### Heads

```text
A. Weighted BCE
   all TP + random TN + train HARD_FP

B. Weighted BCE
   + λ · softplus(-(score_TP - score_HARD_FP))
```

Grid:

```text
hard fraction = 25%, 50%
lambda = 0, 0.1, 0.3, 1.0
```

`lambda=0` — BCE-only.

LOW_TP входит в обычные positives, но отдельной loss/oversampling для LOW_TP нет.
LOW_TP здесь только diagnostic group.

Конфигурация выбирается **по AP на естественном фоне held-out train-contig**.
Validation используется один раз после выбора.

In [1]:
from pathlib import Path
import copy
import gc
import json
import math
import sys
import time

import numpy as np
import pandas as pd
from IPython.display import display

import torch
from torch import nn
import torch.nn.functional as F
import torch_directml

from scipy.stats import pearsonr, rankdata

CURRENT_DIR = Path.cwd().resolve()

PROJECT_ROOT = next(
    candidate
    for candidate in (CURRENT_DIR, *CURRENT_DIR.parents)
    if (candidate / "README.md").is_file()
    and (candidate / "src/ml_project").is_dir()
)

SRC_DIR = PROJECT_ROOT / "src"

if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from ml_project.epic_baseline import load_baseline_sequences
from ml_project.epic_cnn import (
    ProfileWindowConfig,
    ProfileWindowGenerator,
    create_cnn_presence_intensity,
)
from ml_project.epic_data import load_split

device = torch_directml.device()

print("Project:", PROJECT_ROOT)
print("DirectML:", device)
print("GPU:", torch_directml.device_name(0))

Project: D:\Projects\EPIC\EPIC
DirectML: privateuseone:0
GPU: AMD Radeon RX 6750 GRE 12GB 

In [2]:
split = load_split(PROJECT_ROOT)
sequences, fasta_alphabet = load_baseline_sequences(split)

profile_config = ProfileWindowConfig(
    target_length=1024,
    context_flank=130,
    positive_branch_fraction=0.5,
)

EXP036_RUN = (
    PROJECT_ROOT
    / "artifacts"
    / "experiments"
    / "CNN_EXP036_WIDTH64_RF1029"
    / "run_001"
)

EXP036_CHECKPOINT = EXP036_RUN / "width64_final.pt"
EXP036_RESULT = EXP036_RUN / "EXP036_WIDTH64_RESULT.json"

assert EXP036_CHECKPOINT.is_file(), EXP036_CHECKPOINT

checkpoint = torch.load(
    EXP036_CHECKPOINT,
    map_location="cpu",
    weights_only=False,
)

frozen_model = create_cnn_presence_intensity()
frozen_model.load_state_dict(checkpoint["model_state_dict"])

assert frozen_model.backbone.stem.out_channels == 64
assert frozen_model.profile_head.in_channels == 64
assert frozen_model.profile_head.out_channels == 2

rf = 1
for block in frozen_model.backbone.blocks:
    for conv in (block.conv1, block.conv2):
        rf += (int(conv.kernel_size[0]) - 1) * int(conv.dilation[0])

assert rf == 1029

for p in frozen_model.parameters():
    p.requires_grad_(False)

frozen_model = frozen_model.to(device)
frozen_model.eval()

old_presence_weight = (
    frozen_model.profile_head.weight[0, :, 0]
    .detach().cpu().numpy().astype(np.float32, copy=True)
)
old_presence_bias = float(
    frozen_model.profile_head.bias[0].detach().cpu().item()
)

print("Checkpoint:", EXP036_CHECKPOINT)
print("Channels:", frozen_model.backbone.stem.out_channels)
print("RF:", rf)
print("Backbone frozen:", all(not p.requires_grad for p in frozen_model.backbone.parameters()))

if EXP036_RESULT.is_file():
    exp036_result = json.loads(EXP036_RESULT.read_text(encoding="utf-8"))
    display(pd.DataFrame([exp036_result["overall"]]))

Checkpoint: D:\Projects\EPIC\EPIC\artifacts\experiments\CNN_EXP036_WIDTH64_RF1029\run_001\width64_final.pt
Channels: 64
RF: 1029
Backbone frozen: True

,positive_n,presence_AP_5dp,presence_EPIC_Spearman_raw,presence_EPIC_Spearman_5dp,intensity_EPIC_Spearman_raw
0,56205,0.033997,0.177041,0.152906,0.188709

In [3]:
train_generator = ProfileWindowGenerator(
    prepared_split=split,
    sequences=sequences,
    part="train",
    config=profile_config,
    seed=42,
)

validation_generator = ProfileWindowGenerator(
    prepared_split=split,
    sequences=sequences,
    part="validation",
    config=profile_config,
    seed=42,
)

train_tiles = train_generator.tile_index.copy().reset_index(drop=True)
validation_tiles = validation_generator.tile_index.copy().reset_index(drop=True)

TRAIN_CONTIGS = sorted(train_tiles["contig"].astype(str).unique())
VALIDATION_CONTIGS = sorted(validation_tiles["contig"].astype(str).unique())

print("Train contigs:", len(TRAIN_CONTIGS), TRAIN_CONTIGS)
print("Validation contigs:", len(VALIDATION_CONTIGS), VALIDATION_CONTIGS)
print("Train tiles:", len(train_tiles))
print("Validation tiles:", len(validation_tiles))

Train contigs: 9 ['NC_064035.1', 'NC_064036.1', 'NC_064038.1', 'NC_064039.1', 'NC_064040.1', 'NC_064043.1', 'NC_064045.1', 'NC_064047.1', 'NC_064048.1']
Validation contigs: 3 ['NC_064034.1', 'NC_064041.1', 'NC_064042.1']
Train tiles: 130525
Validation tiles: 47743

## 1. Train feature bank

По exhaustive train tiles собираем:

- **все TP**;
- случайные TN;
- HARD_FP candidates по старой WIDTH64 presence-head.

HARD_FP берутся только из train.

In [4]:
EXPERIMENT_ID = "CNN-EXP-037"
EXPERIMENT_SLUG = "CNN_EXP037_FROZEN_WIDTH64_HARDFP_RERANKER"

RUN_DIR = (
    PROJECT_ROOT
    / "artifacts"
    / "experiments"
    / EXPERIMENT_SLUG
    / "run_001"
)
RUN_DIR.mkdir(parents=True, exist_ok=True)

FEATURE_BANK_PATH = RUN_DIR / "train_feature_bank_width64.npz"

RANDOM_TN_PER_TILE_STRAND = 4
HARD_CANDIDATES_PER_TILE_STRAND = 4
MAX_HARD_FP_PER_CONTIG = 50_000
FEATURE_PROGRESS_EVERY = 250

print("Artifacts:", RUN_DIR)
print("Feature bank:", FEATURE_BANK_PATH)

Artifacts: D:\Projects\EPIC\EPIC\artifacts\experiments\CNN_EXP037_FROZEN_WIDTH64_HARDFP_RERANKER\run_001
Feature bank: D:\Projects\EPIC\EPIC\artifacts\experiments\CNN_EXP037_FROZEN_WIDTH64_HARDFP_RERANKER\run_001\train_feature_bank_width64.npz

In [5]:
def sigmoid_numpy(x):
    x = np.asarray(x, dtype=np.float64)
    out = np.empty_like(x, dtype=np.float64)

    positive = x >= 0
    out[positive] = 1.0 / (1.0 + np.exp(-x[positive]))

    exp_x = np.exp(x[~positive])
    out[~positive] = exp_x / (1.0 + exp_x)

    return out.astype(np.float32)


def extract_backbone_and_old_outputs(model, batch):
    # Returns central-crop CPU arrays:
    # features       [2B, L, 64]
    # presence_logit [2B, L]
    # intensity      [2B, L]
    x_gpu = batch.x_both_strands.to(device)

    feature_gpu = model.backbone(x_gpu)
    output_gpu = model.profile_head(feature_gpu)

    c = profile_config.context_flank
    L = profile_config.target_length

    feature = (
        feature_gpu[:, :, c:c + L]
        .permute(0, 2, 1)
        .detach().cpu().numpy()
        .astype(np.float32, copy=True)
    )

    output = (
        output_gpu[:, :, c:c + L]
        .detach().cpu().numpy()
        .astype(np.float32, copy=True)
    )

    presence_logit = output[:, 0, :]
    intensity = output[:, 1, :]

    del x_gpu, feature_gpu, output_gpu

    return feature, presence_logit, intensity

In [6]:
if FEATURE_BANK_PATH.is_file():
    print("Feature bank already exists:", FEATURE_BANK_PATH)

else:
    rng = np.random.default_rng(20260924)

    pos_X = []
    pos_old_score = []
    pos_count = []
    pos_contig = []

    random_X = []
    random_old_score = []
    random_contig = []

    hard_X = []
    hard_old_score = []
    hard_contig = []

    started = time.perf_counter()
    positions_seen = 0

    frozen_model.eval()

    with torch.no_grad():
        for row_i in range(len(train_tiles)):
            selected = train_tiles.iloc[row_i:row_i + 1]
            batch = train_generator.make_batch(selected)

            features, old_logit, _ = extract_backbone_and_old_outputs(
                frozen_model,
                batch,
            )

            old_probability = sigmoid_numpy(old_logit)

            plus_count = (
                batch.count[0, 0, :]
                .numpy().astype(np.float32, copy=False)
            )
            minus_count_reverse = (
                batch.count[0, 1, :]
                .flip(-1)
                .numpy().astype(np.float32, copy=False)
            )

            plus_mask = (
                batch.mask[0, 0, :]
                .numpy().astype(bool, copy=False)
            )
            minus_mask_reverse = (
                batch.mask[0, 1, :]
                .flip(-1)
                .numpy().astype(bool, copy=False)
            )

            contig = str(selected.iloc[0]["contig"])

            for orient_i, (count, mask) in enumerate(
                (
                    (plus_count, plus_mask),
                    (minus_count_reverse, minus_mask_reverse),
                )
            ):
                feat = features[orient_i]
                probability = old_probability[orient_i]

                valid_index = np.flatnonzero(mask)

                positive_index = valid_index[
                    count[valid_index] > 0
                ]
                negative_index = valid_index[
                    count[valid_index] == 0
                ]

                if len(positive_index):
                    pos_X.append(feat[positive_index].copy())
                    pos_old_score.append(probability[positive_index].copy())
                    pos_count.append(count[positive_index].copy())
                    pos_contig.extend([contig] * len(positive_index))

                if len(negative_index):
                    n_random = min(
                        RANDOM_TN_PER_TILE_STRAND,
                        len(negative_index),
                    )
                    random_index = rng.choice(
                        negative_index,
                        size=n_random,
                        replace=False,
                    )

                    random_X.append(feat[random_index].copy())
                    random_old_score.append(probability[random_index].copy())
                    random_contig.extend([contig] * len(random_index))

                    n_hard = min(
                        HARD_CANDIDATES_PER_TILE_STRAND,
                        len(negative_index),
                    )
                    negative_score = probability[negative_index]

                    if len(negative_index) <= n_hard:
                        hard_index = negative_index
                    else:
                        local_top = np.argpartition(
                            negative_score,
                            -n_hard,
                        )[-n_hard:]
                        hard_index = negative_index[local_top]

                    hard_X.append(feat[hard_index].copy())
                    hard_old_score.append(probability[hard_index].copy())
                    hard_contig.extend([contig] * len(hard_index))

                positions_seen += int(mask.sum())

            del (
                batch,
                selected,
                features,
                old_logit,
                old_probability,
                plus_count,
                minus_count_reverse,
                plus_mask,
                minus_mask_reverse,
            )

            done = row_i + 1

            if (
                done == 1
                or done % FEATURE_PROGRESS_EVERY == 0
                or done == len(train_tiles)
            ):
                elapsed = time.perf_counter() - started
                print(
                    f"tiles={done:>6}/{len(train_tiles)} "
                    f"positions={positions_seen:>13,} "
                    f"positions/s={positions_seen / elapsed:,.0f}"
                )

            if done % 50 == 0:
                gc.collect()

    pos_X = np.concatenate(pos_X, axis=0)
    pos_old_score = np.concatenate(pos_old_score)
    pos_count = np.concatenate(pos_count)
    pos_contig = np.asarray(pos_contig)

    random_X = np.concatenate(random_X, axis=0)
    random_old_score = np.concatenate(random_old_score)
    random_contig = np.asarray(random_contig)

    hard_X = np.concatenate(hard_X, axis=0)
    hard_old_score = np.concatenate(hard_old_score)
    hard_contig = np.asarray(hard_contig)

    hard_keep_parts = []

    for contig in TRAIN_CONTIGS:
        idx = np.flatnonzero(hard_contig == contig)

        if len(idx) > MAX_HARD_FP_PER_CONTIG:
            local = np.argpartition(
                hard_old_score[idx],
                -MAX_HARD_FP_PER_CONTIG,
            )[-MAX_HARD_FP_PER_CONTIG:]
            idx = idx[local]

        hard_keep_parts.append(idx)

    hard_keep = np.concatenate(hard_keep_parts)

    hard_X = hard_X[hard_keep]
    hard_old_score = hard_old_score[hard_keep]
    hard_contig = hard_contig[hard_keep]

    np.savez_compressed(
        FEATURE_BANK_PATH,
        pos_X=pos_X,
        pos_old_score=pos_old_score,
        pos_count=pos_count,
        pos_contig=pos_contig,
        random_X=random_X,
        random_old_score=random_old_score,
        random_contig=random_contig,
        hard_X=hard_X,
        hard_old_score=hard_old_score,
        hard_contig=hard_contig,
    )

    print("TP:", pos_X.shape)
    print("Random TN:", random_X.shape)
    print("HARD_FP:", hard_X.shape)
    print("Saved:", FEATURE_BANK_PATH)

tiles=     1/130525 positions=          498 positions/s=12,776
tiles=   250/130525 positions=      374,670 positions/s=236,285
tiles=   500/130525 positions=      811,248 positions/s=253,131
tiles=   750/130525 positions=    1,209,988 positions/s=258,785
tiles=  1000/130525 positions=    1,606,742 positions/s=261,324
tiles=  1250/130525 positions=    2,025,652 positions/s=268,006
tiles=  1500/130525 positions=    2,447,804 positions/s=273,437
tiles=  1750/130525 positions=    2,875,410 positions/s=279,021
tiles=  2000/130525 positions=    3,276,578 positions/s=279,260
tiles=  2250/130525 positions=    3,727,040 positions/s=284,197
tiles=  2500/130525 positions=    4,184,270 positions/s=289,039
tiles=  2750/130525 positions=    4,626,284 positions/s=291,881
tiles=  3000/130525 positions=    5,062,232 positions/s=294,046
tiles=  3250/130525 positions=    5,524,502 positions/s=297,525
tiles=  3500/130525 positions=    5,960,950 positions/s=298,534
tiles=  3750/130525 positions=    6,421,794 positions/s=300,991
tiles=  4000/130525 positions=    6,859,048 positions/s=302,187
tiles=  4250/130525 positions=    7,299,348 positions/s=303,396
tiles=  4500/130525 positions=    7,756,778 positions/s=305,146
tiles=  4750/130525 positions=    8,210,538 positions/s=306,546
tiles=  5000/130525 positions=    8,656,002 positions/s=307,061
tiles=  5250/130525 positions=    9,101,054 positions/s=307,920
tiles=  5500/130525 positions=    9,573,816 positions/s=309,670
tiles=  5750/130525 positions=   10,015,794 positions/s=310,367
tiles=  6000/130525 positions=   10,465,638 positions/s=311,180
tiles=  6250/130525 positions=   10,912,152 positions/s=311,691
tiles=  6500/130525 positions=   11,333,008 positions/s=311,295
tiles=  6750/130525 positions=   11,771,484 positions/s=311,703
tiles=  7000/130525 positions=   12,200,608 positions/s=311,769
tiles=  7250/130525 positions=   12,659,838 positions/s=312,495
tiles=  7500/130525 positions=   13,098,322 positions/s=312,626
tiles=  7750/130525 positions=   13,534,950 positions/s=312,684
tiles=  8000/130525 positions=   13,994,822 positions/s=313,452
tiles=  8250/130525 positions=   14,462,576 positions/s=314,413
tiles=  8500/130525 positions=   14,901,088 positions/s=314,761
tiles=  8750/130525 positions=   15,365,308 positions/s=315,502
tiles=  9000/130525 positions=   15,810,964 positions/s=315,735
tiles=  9250/130525 positions=   16,250,422 positions/s=315,944
tiles=  9500/130525 positions=   16,695,200 positions/s=316,144
tiles=  9750/130525 positions=   17,137,850 positions/s=316,459
tiles= 10000/130525 positions=   17,603,050 positions/s=316,912
tiles= 10250/130525 positions=   18,053,340 positions/s=317,056
tiles= 10500/130525 positions=   18,516,046 positions/s=317,605
tiles= 10750/130525 positions=   18,972,510 positions/s=317,850
tiles= 11000/130525 positions=   19,394,816 positions/s=317,583
tiles= 11250/130525 positions=   19,837,696 positions/s=317,533
tiles= 11500/130525 positions=   20,271,614 positions/s=317,475
tiles= 11750/130525 positions=   20,681,734 positions/s=317,064
tiles= 12000/130525 positions=   21,114,720 positions/s=316,792
tiles= 12250/130525 positions=   21,567,178 positions/s=317,054
tiles= 12500/130525 positions=   22,029,588 positions/s=317,408
tiles= 12750/130525 positions=   22,496,296 positions/s=317,640
tiles= 13000/130525 positions=   22,952,444 positions/s=317,821
tiles= 13250/130525 positions=   23,405,132 positions/s=317,984
tiles= 13500/130525 positions=   23,857,290 positions/s=318,214
tiles= 13750/130525 positions=   24,245,722 positions/s=317,383
tiles= 14000/130525 positions=   24,704,222 positions/s=317,681
tiles= 14250/130525 positions=   25,164,024 positions/s=317,956
tiles= 14500/130525 positions=   25,624,020 positions/s=318,210
tiles= 14750/130525 positions=   26,082,418 positions/s=318,383
tiles= 15000/130525 positions=   26,528,506 positions/s=318,595
tiles= 15250/130525 positions=   26,974,386 positions/s=318,731
tiles= 15500/130525 positions=   27,411,642 positions/s=318,702
tiles= 15750/130525 positions=   27,853,676 positions/s=318,684
tiles= 16000/130525 positions=   28,306,126 positions/s=318,394
tiles= 16250/130525 positions=   28,769,036 positions/s=318,254
tiles= 16500/130525 positions=   29,227,506 positions/s=318,041
tiles= 16750/130525 positions=   29,695,424 positions/s=318,207
tiles= 17000/130525 positions=   30,170,706 positions/s=318,636
tiles= 17250/130525 positions=   30,600,446 positions/s=318,307
tiles= 17500/130525 positions=   31,017,264 positions/s=318,106
tiles= 17750/130525 positions=   31,454,206 positions/s=318,119
tiles= 18000/130525 positions=   31,921,728 positions/s=318,428
tiles= 18250/130525 positions=   32,348,840 positions/s=318,301
tiles= 18500/130525 positions=   32,745,366 positions/s=317,858
tiles= 18750/130525 positions=   33,168,042 positions/s=317,689
tiles= 19000/130525 positions=   33,560,688 positions/s=317,145
tiles= 19250/130525 positions=   33,851,438 positions/s=315,742
tiles= 19500/130525 positions=   34,259,324 positions/s=315,397
tiles= 19750/130525 positions=   34,666,804 positions/s=315,065
tiles= 20000/130525 positions=   35,089,842 positions/s=314,874
tiles= 20250/130525 positions=   35,519,864 positions/s=314,813
tiles= 20500/130525 positions=   35,974,200 positions/s=314,922
tiles= 20750/130525 positions=   36,416,102 positions/s=314,882
tiles= 21000/130525 positions=   36,866,230 positions/s=314,961
tiles= 21250/130525 positions=   37,311,294 positions/s=314,968
tiles= 21500/130525 positions=   37,754,652 positions/s=314,970
tiles= 21750/130525 positions=   38,209,728 positions/s=315,082
tiles= 22000/130525 positions=   38,621,208 positions/s=314,760
tiles= 22250/130525 positions=   39,070,956 positions/s=314,885
tiles= 22500/130525 positions=   39,525,378 positions/s=315,017
tiles= 22750/130525 positions=   39,966,740 positions/s=314,902
tiles= 23000/130525 positions=   40,422,020 positions/s=315,042
tiles= 23250/130525 positions=   40,882,498 positions/s=315,215
tiles= 23500/130525 positions=   41,346,732 positions/s=315,460
tiles= 23750/130525 positions=   41,809,468 positions/s=314,966
tiles= 24000/130525 positions=   42,268,032 positions/s=314,715
tiles= 24250/130525 positions=   42,734,368 positions/s=314,568
tiles= 24500/130525 positions=   43,194,106 positions/s=314,366
tiles= 24750/130525 positions=   43,634,392 positions/s=314,183
tiles= 25000/130525 positions=   44,102,562 positions/s=314,113
tiles= 25250/130525 positions=   44,552,854 positions/s=314,128
tiles= 25500/130525 positions=   45,021,054 positions/s=314,473
tiles= 25750/130525 positions=   45,476,470 positions/s=314,637
tiles= 26000/130525 positions=   45,922,610 positions/s=314,587
tiles= 26250/130525 positions=   46,387,806 positions/s=314,695
tiles= 26500/130525 positions=   46,836,708 positions/s=314,726
tiles= 26750/130525 positions=   47,295,144 positions/s=314,707
tiles= 27000/130525 positions=   47,747,326 positions/s=314,759
tiles= 27250/130525 positions=   48,170,222 positions/s=314,565
tiles= 27500/130525 positions=   48,609,702 positions/s=314,540
tiles= 27750/130525 positions=   49,059,464 positions/s=314,421
tiles= 28000/130525 positions=   49,512,028 positions/s=314,597
tiles= 28250/130525 positions=   49,950,740 positions/s=314,455
tiles= 28500/130525 positions=   50,392,888 positions/s=314,105
tiles= 28750/130525 positions=   50,835,458 positions/s=313,640
tiles= 29000/130525 positions=   51,283,394 positions/s=313,458
tiles= 29250/130525 positions=   51,755,290 positions/s=313,428
tiles= 29500/130525 positions=   52,218,734 positions/s=313,525
tiles= 29750/130525 positions=   52,681,126 positions/s=313,672
tiles= 30000/130525 positions=   53,145,896 positions/s=313,804
tiles= 30250/130525 positions=   53,619,734 positions/s=314,009
tiles= 30500/130525 positions=   54,079,210 positions/s=314,076
tiles= 30750/130525 positions=   54,516,270 positions/s=314,042
tiles= 31000/130525 positions=   54,960,156 positions/s=314,072
tiles= 31250/130525 positions=   55,421,252 positions/s=314,130
tiles= 31500/130525 positions=   55,860,384 positions/s=314,035
tiles= 31750/130525 positions=   56,296,412 positions/s=313,937
tiles= 32000/130525 positions=   56,739,322 positions/s=313,917
tiles= 32250/130525 positions=   57,170,444 positions/s=313,816
tiles= 32500/130525 positions=   57,617,800 positions/s=313,712
tiles= 32750/130525 positions=   58,079,558 positions/s=313,822
tiles= 33000/130525 positions=   58,536,052 positions/s=313,738
tiles= 33250/130525 positions=   58,963,434 positions/s=313,639
tiles= 33500/130525 positions=   59,408,218 positions/s=313,655
tiles= 33750/130525 positions=   59,863,404 positions/s=313,736
tiles= 34000/130525 positions=   60,277,890 positions/s=313,547
tiles= 34250/130525 positions=   60,719,226 positions/s=313,514
tiles= 34500/130525 positions=   61,163,284 positions/s=313,482
tiles= 34750/130525 positions=   61,613,518 positions/s=313,497
tiles= 35000/130525 positions=   62,047,412 positions/s=313,406
tiles= 35250/130525 positions=   62,486,668 positions/s=313,374
tiles= 35500/130525 positions=   62,882,304 positions/s=313,172
tiles= 35750/130525 positions=   63,314,676 positions/s=313,124
tiles= 36000/130525 positions=   63,743,882 positions/s=313,073
tiles= 36250/130525 positions=   64,213,812 positions/s=313,200
tiles= 36500/130525 positions=   64,636,248 positions/s=313,167
tiles= 36750/130525 positions=   65,062,130 positions/s=313,038
tiles= 37000/130525 positions=   65,433,170 positions/s=312,655
tiles= 37250/130525 positions=   65,782,764 positions/s=312,266
tiles= 37500/130525 positions=   66,141,318 positions/s=311,872
tiles= 37750/130525 positions=   66,544,268 positions/s=311,727
tiles= 38000/130525 positions=   66,930,142 positions/s=311,495
tiles= 38250/130525 positions=   67,283,474 positions/s=311,055
tiles= 38500/130525 positions=   67,655,908 positions/s=310,725
tiles= 38750/130525 positions=   68,060,764 positions/s=310,597
tiles= 39000/130525 positions=   68,497,324 positions/s=310,626
tiles= 39250/130525 positions=   68,931,060 positions/s=310,575
tiles= 39500/130525 positions=   69,370,112 positions/s=310,582
tiles= 39750/130525 positions=   69,801,212 positions/s=310,568
tiles= 40000/130525 positions=   70,254,276 positions/s=310,637
tiles= 40250/130525 positions=   70,684,908 positions/s=310,621
tiles= 40500/130525 positions=   71,121,452 positions/s=310,596
tiles= 40750/130525 positions=   71,540,522 positions/s=310,473
tiles= 41000/130525 positions=   71,992,190 positions/s=310,503
tiles= 41250/130525 positions=   72,443,112 positions/s=310,561
tiles= 41500/130525 positions=   72,904,514 positions/s=310,668
tiles= 41750/130525 positions=   73,362,076 positions/s=310,755
tiles= 42000/130525 positions=   73,805,640 positions/s=310,771
tiles= 42250/130525 positions=   74,227,776 positions/s=310,712
tiles= 42500/130525 positions=   74,636,500 positions/s=310,610
tiles= 42750/130525 positions=   75,072,004 positions/s=310,620
tiles= 43000/130525 positions=   75,526,296 positions/s=310,663
tiles= 43250/130525 positions=   75,976,300 positions/s=310,728
tiles= 43500/130525 positions=   76,394,912 positions/s=310,592
tiles= 43750/130525 positions=   76,835,172 positions/s=310,613
tiles= 44000/130525 positions=   77,299,910 positions/s=310,737
tiles= 44250/130525 positions=   77,742,842 positions/s=310,740
tiles= 44500/130525 positions=   78,206,896 positions/s=310,834
tiles= 44750/130525 positions=   78,661,360 positions/s=310,856
tiles= 45000/130525 positions=   79,087,226 positions/s=310,797
tiles= 45250/130525 positions=   79,522,492 positions/s=310,767
tiles= 45500/130525 positions=   79,955,406 positions/s=310,737
tiles= 45750/130525 positions=   80,409,790 positions/s=310,785
tiles= 46000/130525 positions=   80,854,546 positions/s=310,800
tiles= 46250/130525 positions=   81,284,140 positions/s=310,745
tiles= 46500/130525 positions=   81,740,176 positions/s=310,789
tiles= 46750/130525 positions=   82,190,128 positions/s=310,800
tiles= 47000/130525 positions=   82,658,690 positions/s=310,894
tiles= 47250/130525 positions=   83,088,376 positions/s=310,834
tiles= 47500/130525 positions=   83,538,284 positions/s=310,851
tiles= 47750/130525 positions=   83,973,716 positions/s=310,827
tiles= 48000/130525 positions=   84,397,086 positions/s=310,764
tiles= 48250/130525 positions=   84,811,340 positions/s=310,667
tiles= 48500/130525 positions=   85,263,740 positions/s=310,680
tiles= 48750/130525 positions=   85,724,970 positions/s=310,710
tiles= 49000/130525 positions=   86,180,046 positions/s=310,766
tiles= 49250/130525 positions=   86,631,256 positions/s=310,805
tiles= 49500/130525 positions=   87,087,060 positions/s=310,870
tiles= 49750/130525 positions=   87,558,542 positions/s=311,007
tiles= 50000/130525 positions=   88,017,984 positions/s=311,054
tiles= 50250/130525 positions=   88,454,012 positions/s=311,018
tiles= 50500/130525 positions=   88,869,248 positions/s=310,904
tiles= 50750/130525 positions=   89,244,566 positions/s=310,680
tiles= 51000/130525 positions=   89,615,724 positions/s=310,441
tiles= 51250/130525 positions=   90,018,204 positions/s=310,300
tiles= 51500/130525 positions=   90,416,444 positions/s=310,165
tiles= 51750/130525 positions=   90,849,394 positions/s=310,118
tiles= 52000/130525 positions=   91,270,744 positions/s=310,077
tiles= 52250/130525 positions=   91,687,048 positions/s=309,965
tiles= 52500/130525 positions=   92,097,876 positions/s=309,605
tiles= 52750/130525 positions=   92,546,938 positions/s=309,550
tiles= 53000/130525 positions=   92,956,772 positions/s=309,357
tiles= 53250/130525 positions=   93,393,530 positions/s=309,242
tiles= 53500/130525 positions=   93,836,490 positions/s=309,203
tiles= 53750/130525 positions=   94,290,696 positions/s=309,217
tiles= 54000/130525 positions=   94,764,042 positions/s=309,212
tiles= 54250/130525 positions=   95,209,610 positions/s=309,134
tiles= 54500/130525 positions=   95,680,956 positions/s=309,195
tiles= 54750/130525 positions=   96,135,532 positions/s=309,253
tiles= 55000/130525 positions=   96,591,158 positions/s=309,309
tiles= 55250/130525 positions=   97,062,680 positions/s=309,341
tiles= 55500/130525 positions=   97,521,758 positions/s=309,379
tiles= 55750/130525 positions=   97,980,720 positions/s=309,334
tiles= 56000/130525 positions=   98,421,494 positions/s=309,281
tiles= 56250/130525 positions=   98,880,076 positions/s=309,409
tiles= 56500/130525 positions=   99,314,818 positions/s=309,399
tiles= 56750/130525 positions=   99,769,914 positions/s=309,397
tiles= 57000/130525 positions=  100,228,654 positions/s=309,369
tiles= 57250/130525 positions=  100,668,700 positions/s=309,341
tiles= 57500/130525 positions=  101,137,786 positions/s=309,389
tiles= 57750/130525 positions=  101,595,212 positions/s=309,422
tiles= 58000/130525 positions=  102,050,630 positions/s=309,214
tiles= 58250/130525 positions=  102,490,700 positions/s=308,924
tiles= 58500/130525 positions=  102,946,236 positions/s=308,732
tiles= 58750/130525 positions=  103,404,498 positions/s=308,647
tiles= 59000/130525 positions=  103,833,178 positions/s=308,456
tiles= 59250/130525 positions=  104,275,576 positions/s=308,365
tiles= 59500/130525 positions=  104,715,990 positions/s=308,258
tiles= 59750/130525 positions=  105,159,184 positions/s=308,117
tiles= 60000/130525 positions=  105,612,078 positions/s=307,968
tiles= 60250/130525 positions=  106,073,096 positions/s=307,817
tiles= 60500/130525 positions=  106,546,696 positions/s=307,678
tiles= 60750/130525 positions=  107,017,948 positions/s=307,546
tiles= 61000/130525 positions=  107,467,844 positions/s=307,420
tiles= 61250/130525 positions=  107,914,924 positions/s=307,308
tiles= 61500/130525 positions=  108,367,498 positions/s=307,097
tiles= 61750/130525 positions=  108,818,006 positions/s=306,968
tiles= 62000/130525 positions=  109,266,602 positions/s=306,895
tiles= 62250/130525 positions=  109,738,972 positions/s=306,915
tiles= 62500/130525 positions=  110,191,754 positions/s=306,898
tiles= 62750/130525 positions=  110,637,676 positions/s=306,891
tiles= 63000/130525 positions=  111,088,044 positions/s=306,894
tiles= 63250/130525 positions=  111,548,072 positions/s=306,934
tiles= 63500/130525 positions=  111,987,202 positions/s=306,912
tiles= 63750/130525 positions=  112,448,542 positions/s=306,821
tiles= 64000/130525 positions=  112,899,692 positions/s=306,768
tiles= 64250/130525 positions=  113,330,184 positions/s=306,659
tiles= 64500/130525 positions=  113,785,232 positions/s=306,637
tiles= 64750/130525 positions=  114,228,690 positions/s=306,490
tiles= 65000/130525 positions=  114,688,278 positions/s=306,419
tiles= 65250/130525 positions=  115,154,262 positions/s=306,432
tiles= 65500/130525 positions=  115,587,290 positions/s=306,366
tiles= 65750/130525 positions=  116,029,644 positions/s=306,317
tiles= 66000/130525 positions=  116,423,864 positions/s=306,103
tiles= 66250/130525 positions=  116,878,554 positions/s=306,026
tiles= 66500/130525 positions=  117,318,190 positions/s=305,872
tiles= 66750/130525 positions=  117,744,608 positions/s=305,674
tiles= 67000/130525 positions=  118,099,728 positions/s=305,387
tiles= 67250/130525 positions=  118,440,368 positions/s=305,092
tiles= 67500/130525 positions=  118,812,842 positions/s=304,871
tiles= 67750/130525 positions=  119,229,292 positions/s=304,772
tiles= 68000/130525 positions=  119,664,714 positions/s=304,671
tiles= 68250/130525 positions=  120,127,276 positions/s=304,583
tiles= 68500/130525 positions=  120,551,090 positions/s=304,449
tiles= 68750/130525 positions=  120,999,788 positions/s=304,216
tiles= 69000/130525 positions=  121,397,052 positions/s=303,869
tiles= 69250/130525 positions=  121,843,378 positions/s=303,755
tiles= 69500/130525 positions=  122,286,810 positions/s=303,639
tiles= 69750/130525 positions=  122,705,426 positions/s=303,537
tiles= 70000/130525 positions=  123,142,212 positions/s=303,489
tiles= 70250/130525 positions=  123,576,290 positions/s=303,443
tiles= 70500/130525 positions=  123,986,428 positions/s=303,320
tiles= 70750/130525 positions=  124,426,084 positions/s=303,305
tiles= 71000/130525 positions=  124,893,706 positions/s=303,347
tiles= 71250/130525 positions=  125,364,750 positions/s=303,406
tiles= 71500/130525 positions=  125,818,834 positions/s=303,178
tiles= 71750/130525 positions=  126,256,936 positions/s=303,031
tiles= 72000/130525 positions=  126,730,436 positions/s=302,991
tiles= 72250/130525 positions=  127,203,932 positions/s=303,018
tiles= 72500/130525 positions=  127,667,994 positions/s=302,980
tiles= 72750/130525 positions=  128,126,676 positions/s=302,958
tiles= 73000/130525 positions=  128,585,800 positions/s=302,925
tiles= 73250/130525 positions=  129,039,962 positions/s=302,763
tiles= 73500/130525 positions=  129,498,946 positions/s=302,736
tiles= 73750/130525 positions=  129,940,816 positions/s=302,662
tiles= 74000/130525 positions=  130,394,498 positions/s=302,605
tiles= 74250/130525 positions=  130,830,438 positions/s=302,534
tiles= 74500/130525 positions=  131,251,334 positions/s=302,442
tiles= 74750/130525 positions=  131,692,706 positions/s=302,389
tiles= 75000/130525 positions=  132,130,514 positions/s=302,319
tiles= 75250/130525 positions=  132,571,756 positions/s=302,266
tiles= 75500/130525 positions=  133,013,368 positions/s=302,219
tiles= 75750/130525 positions=  133,471,648 positions/s=302,212
tiles= 76000/130525 positions=  133,907,070 positions/s=302,101
tiles= 76250/130525 positions=  134,367,846 positions/s=302,045
tiles= 76500/130525 positions=  134,790,198 positions/s=301,951
tiles= 76750/130525 positions=  135,240,702 positions/s=301,939
tiles= 77000/130525 positions=  135,687,992 positions/s=301,874
tiles= 77250/130525 positions=  136,150,314 positions/s=301,733
tiles= 77500/130525 positions=  136,607,880 positions/s=301,741
tiles= 77750/130525 positions=  137,043,522 positions/s=301,704

In [7]:
bank = np.load(FEATURE_BANK_PATH, allow_pickle=False)

pos_X = bank["pos_X"]
pos_old_score = bank["pos_old_score"]
pos_count = bank["pos_count"]
pos_contig = bank["pos_contig"]

random_X = bank["random_X"]
random_old_score = bank["random_old_score"]
random_contig = bank["random_contig"]

hard_X = bank["hard_X"]
hard_old_score = bank["hard_old_score"]
hard_contig = bank["hard_contig"]

print("TP:", pos_X.shape)
print("Random TN:", random_X.shape)
print("HARD_FP:", hard_X.shape)

display(
    pd.DataFrame(
        {
            "contig": TRAIN_CONTIGS,
            "TP": [int(np.sum(pos_contig == c)) for c in TRAIN_CONTIGS],
            "random_TN": [int(np.sum(random_contig == c)) for c in TRAIN_CONTIGS],
            "HARD_FP": [int(np.sum(hard_contig == c)) for c in TRAIN_CONTIGS],
        }
    )
)

TP: (170443, 64)
Random TN: (1044002, 64)
HARD_FP: (450000, 64)

        contig     TP  random_TN  HARD_FP
0  NC_064035.1  30987     151318    50000
1  NC_064036.1  26323     142686    50000
2  NC_064038.1  14793     117192    50000
3  NC_064039.1  21975     123984    50000
4  NC_064040.1  19067     118478    50000
5  NC_064043.1  19558     109086    50000
6  NC_064045.1  15184      95862    50000
7  NC_064047.1  11668     101970    50000
8  NC_064048.1  10888      83426    50000

## 2. Linear head training

Стандартизация остаётся линейным преобразованием и затем сворачивается обратно
в один `Conv1d(64,1,1)`.

Инициализация головы эквивалентна старой WIDTH64 presence-head.

In [8]:
HEAD_SEED = 20260924
NEGATIVE_MULTIPLIER = 4.0
HEAD_EPOCHS = 40
HEAD_BATCH_SIZE = 8192
HEAD_LR = 3e-3
WEIGHT_DECAY = 1e-4

HARD_FRACTIONS = (0.25, 0.50)
LAMBDAS = (0.0, 0.1, 0.3, 1.0)

CONFIGS = [
    {
        "name": (
            f"hard{int(hard_fraction * 100):02d}_"
            f"lambda{str(lam).replace('.', 'p')}"
        ),
        "hard_fraction": hard_fraction,
        "lambda_rank": lam,
    }
    for hard_fraction in HARD_FRACTIONS
    for lam in LAMBDAS
]

display(pd.DataFrame(CONFIGS))


def fit_scaler(X):
    mean = X.mean(axis=0, dtype=np.float64).astype(np.float32)
    std = X.std(axis=0, dtype=np.float64).astype(np.float32)
    std = np.maximum(std, 1e-6)
    return mean, std


def old_head_in_standardized_space(mean, std):
    w = (old_presence_weight * std).astype(np.float32)
    b = np.float32(
        old_presence_bias
        + np.dot(old_presence_weight, mean)
    )
    return w, b


def train_linear_head(
    *,
    train_pos_X,
    train_random_X,
    train_hard_X,
    hard_fraction,
    lambda_rank,
    seed,
):
    rng = np.random.default_rng(seed)

    scaler_source = np.concatenate(
        (train_pos_X, train_random_X, train_hard_X),
        axis=0,
    )
    mean, std = fit_scaler(scaler_source)
    del scaler_source

    n_pos = len(train_pos_X)
    n_neg_target = int(round(NEGATIVE_MULTIPLIER * n_pos))

    n_hard_target = int(round(hard_fraction * n_neg_target))
    n_random_target = n_neg_target - n_hard_target

    hard_index = rng.choice(
        len(train_hard_X),
        size=n_hard_target,
        replace=n_hard_target > len(train_hard_X),
    )
    random_index = rng.choice(
        len(train_random_X),
        size=n_random_target,
        replace=n_random_target > len(train_random_X),
    )

    X_neg = np.concatenate(
        (
            train_hard_X[hard_index],
            train_random_X[random_index],
        ),
        axis=0,
    )

    X_pos = train_pos_X

    X = np.concatenate((X_pos, X_neg), axis=0)
    y = np.concatenate(
        (
            np.ones(len(X_pos), dtype=np.float32),
            np.zeros(len(X_neg), dtype=np.float32),
        )
    )

    X = ((X - mean) / std).astype(np.float32, copy=False)

    X_hard_pair = (
        (train_hard_X - mean) / std
    ).astype(np.float32, copy=False)

    X_pos_pair = (
        (train_pos_X - mean) / std
    ).astype(np.float32, copy=False)

    linear = nn.Linear(64, 1, bias=True)

    init_w, init_b = old_head_in_standardized_space(mean, std)

    with torch.no_grad():
        linear.weight.copy_(torch.from_numpy(init_w)[None, :])
        linear.bias.fill_(float(init_b))

    optimizer = torch.optim.AdamW(
        linear.parameters(),
        lr=HEAD_LR,
        weight_decay=WEIGHT_DECAY,
    )

    pos_weight = torch.tensor(
        [len(X_neg) / max(len(X_pos), 1)],
        dtype=torch.float32,
    )

    bce = nn.BCEWithLogitsLoss(pos_weight=pos_weight)

    torch.manual_seed(seed)
    n = len(X)

    for epoch in range(HEAD_EPOCHS):
        order = rng.permutation(n)

        for start in range(0, n, HEAD_BATCH_SIZE):
            idx = order[start:start + HEAD_BATCH_SIZE]

            xb = torch.from_numpy(X[idx])
            yb = torch.from_numpy(y[idx])[:, None]

            optimizer.zero_grad(set_to_none=True)

            logit = linear(xb)
            loss = bce(logit, yb)

            if lambda_rank > 0 and len(X_hard_pair) > 0:
                pair_n = min(
                    HEAD_BATCH_SIZE,
                    len(X_pos_pair),
                    len(X_hard_pair),
                )

                pos_idx = rng.choice(
                    len(X_pos_pair),
                    size=pair_n,
                    replace=False,
                )
                hard_idx = rng.choice(
                    len(X_hard_pair),
                    size=pair_n,
                    replace=False,
                )

                pos_logit = linear(
                    torch.from_numpy(X_pos_pair[pos_idx])
                )
                hard_logit = linear(
                    torch.from_numpy(X_hard_pair[hard_idx])
                )

                rank_loss = F.softplus(
                    -(pos_logit - hard_logit)
                ).mean()

                loss = loss + lambda_rank * rank_loss

            loss.backward()
            optimizer.step()

    w_std = (
        linear.weight[0]
        .detach().cpu().numpy()
        .astype(np.float32, copy=True)
    )
    b_std = float(
        linear.bias[0].detach().cpu().item()
    )

    # Fold scaler into a raw-feature linear layer.
    w_raw = (w_std / std).astype(np.float32)
    b_raw = float(
        b_std
        - np.dot(w_raw, mean)
    )

    return {
        "w_raw": w_raw,
        "b_raw": b_raw,
        "mean": mean,
        "std": std,
        "n_pos": int(len(X_pos)),
        "n_neg": int(len(X_neg)),
        "n_hard": int(n_hard_target),
        "n_random": int(n_random_target),
    }

               name  hard_fraction  lambda_rank
0  hard25_lambda0p0           0.25          0.0
1  hard25_lambda0p1           0.25          0.1
2  hard25_lambda0p3           0.25          0.3
3  hard25_lambda1p0           0.25          1.0
4  hard50_lambda0p0           0.50          0.0
5  hard50_lambda0p1           0.50          0.1
6  hard50_lambda0p3           0.50          0.3
7  hard50_lambda1p0           0.50          1.0

In [9]:
SUBMISSION_LEVELS = 100_001


def probability_bin_5dp(probabilities):
    return np.rint(
        np.clip(probabilities, 0.0, 1.0) * 100_000
    ).astype(np.int32)


def update_histogram(hist, indices):
    values, counts = np.unique(indices, return_counts=True)
    hist[values] += counts.astype(np.int64)


def ap_from_histograms(positive_hist, total_hist):
    positives = int(positive_hist.sum())

    if positives <= 0:
        return float("nan")

    pos_desc = positive_hist[::-1]
    total_desc = total_hist[::-1]

    tp = np.cumsum(pos_desc, dtype=np.int64)
    predicted_positive = np.cumsum(total_desc, dtype=np.int64)

    precision = tp / np.maximum(predicted_positive, 1)

    return float(
        np.sum(
            (pos_desc / positives) * precision
        )
    )


def dense_rank_pearson(prediction, target):
    prediction = np.asarray(prediction)
    target = np.asarray(target)

    if len(prediction) < 2:
        return float("nan")

    return float(
        pearsonr(
            rankdata(prediction, method="dense"),
            rankdata(target, method="dense"),
        )[0]
    )


def score_linear_raw(features, w_raw, b_raw):
    logit = features @ w_raw + b_raw
    return sigmoid_numpy(logit)

## 3. Cross-contig CV внутри train

На каждой fold:

```text
8 train-contigs → head training
1 train-contig  → exhaustive natural-background AP
```

Все 8 candidate heads оцениваются на одном проходе backbone.

Primary selection metric: **mean AP**.

In [10]:
cv_heads = {}

for fold_i, heldout_contig in enumerate(TRAIN_CONTIGS, 1):
    print()
    print("=" * 80)
    print(
        f"TRAIN HEADS FOLD {fold_i}/{len(TRAIN_CONTIGS)} "
        f"heldout={heldout_contig}"
    )
    print("=" * 80)

    fold_pos_X = pos_X[pos_contig != heldout_contig]
    fold_random_X = random_X[random_contig != heldout_contig]
    fold_hard_X = hard_X[hard_contig != heldout_contig]

    cv_heads[heldout_contig] = {}

    for config_i, config in enumerate(CONFIGS, 1):
        print(
            f"  {config_i}/{len(CONFIGS)} {config['name']}"
        )

        trained = train_linear_head(
            train_pos_X=fold_pos_X,
            train_random_X=fold_random_X,
            train_hard_X=fold_hard_X,
            hard_fraction=config["hard_fraction"],
            lambda_rank=config["lambda_rank"],
            seed=HEAD_SEED + 1000 * fold_i + config_i,
        )

        cv_heads[heldout_contig][config["name"]] = trained

print("All fold heads trained.")

================================================================================
TRAIN HEADS FOLD 1/9 heldout=NC_064035.1
================================================================================
  1/8 hard25_lambda0p0
  2/8 hard25_lambda0p1
  3/8 hard25_lambda0p3
  4/8 hard25_lambda1p0
  5/8 hard50_lambda0p0
  6/8 hard50_lambda0p1
  7/8 hard50_lambda0p3
  8/8 hard50_lambda1p0

================================================================================
TRAIN HEADS FOLD 2/9 heldout=NC_064036.1
================================================================================
  1/8 hard25_lambda0p0
  2/8 hard25_lambda0p1
  3/8 hard25_lambda0p3
  4/8 hard25_lambda1p0
  5/8 hard50_lambda0p0
  6/8 hard50_lambda0p1
  7/8 hard50_lambda0p3
  8/8 hard50_lambda1p0

================================================================================
TRAIN HEADS FOLD 3/9 heldout=NC_064038.1
================================================================================
  1/8 hard25_lambda0p0
  2/8 hard25_lambda0p1
  3/8 hard25_lambda0p3
  4/8 hard25_lambda1p0
  5/8 hard50_lambda0p0
  6/8 hard50_lambda0p1
  7/8 hard50_lambda0p3
  8/8 hard50_lambda1p0

================================================================================
TRAIN HEADS FOLD 4/9 heldout=NC_064039.1
================================================================================
  1/8 hard25_lambda0p0
  2/8 hard25_lambda0p1
  3/8 hard25_lambda0p3
  4/8 hard25_lambda1p0
  5/8 hard50_lambda0p0
  6/8 hard50_lambda0p1
  7/8 hard50_lambda0p3
  8/8 hard50_lambda1p0

================================================================================
TRAIN HEADS FOLD 5/9 heldout=NC_064040.1
================================================================================
  1/8 hard25_lambda0p0
  2/8 hard25_lambda0p1
  3/8 hard25_lambda0p3
  4/8 hard25_lambda1p0
  5/8 hard50_lambda0p0
  6/8 hard50_lambda0p1
  7/8 hard50_lambda0p3
  8/8 hard50_lambda1p0

================================================================================
TRAIN HEADS FOLD 6/9 heldout=NC_064043.1
================================================================================
  1/8 hard25_lambda0p0
  2/8 hard25_lambda0p1
  3/8 hard25_lambda0p3
  4/8 hard25_lambda1p0
  5/8 hard50_lambda0p0
  6/8 hard50_lambda0p1
  7/8 hard50_lambda0p3
  8/8 hard50_lambda1p0

================================================================================
TRAIN HEADS FOLD 7/9 heldout=NC_064045.1
================================================================================
  1/8 hard25_lambda0p0
  2/8 hard25_lambda0p1
  3/8 hard25_lambda0p3
  4/8 hard25_lambda1p0
  5/8 hard50_lambda0p0
  6/8 hard50_lambda0p1
  7/8 hard50_lambda0p3
  8/8 hard50_lambda1p0

================================================================================
TRAIN HEADS FOLD 8/9 heldout=NC_064047.1
================================================================================
  1/8 hard25_lambda0p0
  2/8 hard25_lambda0p1
  3/8 hard25_lambda0p3
  4/8 hard25_lambda1p0
  5/8 hard50_lambda0p0
  6/8 hard50_lambda0p1
  7/8 hard50_lambda0p3
  8/8 hard50_lambda1p0

================================================================================
TRAIN HEADS FOLD 9/9 heldout=NC_064048.1
================================================================================
  1/8 hard25_lambda0p0
  2/8 hard25_lambda0p1
  3/8 hard25_lambda0p3
  4/8 hard25_lambda1p0
  5/8 hard50_lambda0p0
  6/8 hard50_lambda0p1
  7/8 hard50_lambda0p3
  8/8 hard50_lambda1p0
All fold heads trained.

In [11]:
CV_RESULTS_PATH = RUN_DIR / "cross_contig_cv.csv"

cv_rows = []

frozen_model.eval()

for fold_i, heldout_contig in enumerate(TRAIN_CONTIGS, 1):
    print()
    print("=" * 80)
    print(
        f"EVAL FOLD {fold_i}/{len(TRAIN_CONTIGS)} "
        f"{heldout_contig}"
    )
    print("=" * 80)

    fold_tiles = (
        train_tiles[
            train_tiles["contig"].astype(str) == heldout_contig
        ]
        .reset_index(drop=True)
    )

    states = {
        config["name"]: {
            "total_hist": np.zeros(SUBMISSION_LEVELS, dtype=np.int64),
            "positive_hist": np.zeros(SUBMISSION_LEVELS, dtype=np.int64),
            "positive_score": [],
            "positive_count": [],
        }
        for config in CONFIGS
    }

    started = time.perf_counter()
    positions_seen = 0

    with torch.no_grad():
        for row_i in range(len(fold_tiles)):
            selected = fold_tiles.iloc[row_i:row_i + 1]
            batch = train_generator.make_batch(selected)

            features, _, _ = extract_backbone_and_old_outputs(
                frozen_model,
                batch,
            )

            plus_count = (
                batch.count[0, 0, :]
                .numpy().astype(np.float32, copy=False)
            )
            minus_count_reverse = (
                batch.count[0, 1, :]
                .flip(-1)
                .numpy().astype(np.float32, copy=False)
            )

            plus_mask = (
                batch.mask[0, 0, :]
                .numpy().astype(bool, copy=False)
            )
            minus_mask_reverse = (
                batch.mask[0, 1, :]
                .flip(-1)
                .numpy().astype(bool, copy=False)
            )

            for orient_i, (count, mask) in enumerate(
                (
                    (plus_count, plus_mask),
                    (minus_count_reverse, minus_mask_reverse),
                )
            ):
                valid_index = np.flatnonzero(mask)
                valid_feature = features[orient_i, valid_index]
                valid_count = count[valid_index]
                positive = valid_count > 0

                for config in CONFIGS:
                    name = config["name"]
                    head = cv_heads[heldout_contig][name]

                    probability = score_linear_raw(
                        valid_feature,
                        head["w_raw"],
                        head["b_raw"],
                    )

                    score_bin = probability_bin_5dp(probability)
                    state = states[name]

                    update_histogram(
                        state["total_hist"],
                        score_bin,
                    )

                    if positive.any():
                        update_histogram(
                            state["positive_hist"],
                            score_bin[positive],
                        )

                        state["positive_score"].append(
                            probability[positive].copy()
                        )
                        state["positive_count"].append(
                            valid_count[positive].copy()
                        )

                positions_seen += int(mask.sum())

            del (
                batch,
                selected,
                features,
                plus_count,
                minus_count_reverse,
                plus_mask,
                minus_mask_reverse,
            )

            if (
                row_i == 0
                or (row_i + 1) % 250 == 0
                or row_i + 1 == len(fold_tiles)
            ):
                elapsed = time.perf_counter() - started
                print(
                    f"tiles={row_i + 1:>5}/{len(fold_tiles)} "
                    f"positions={positions_seen:>12,} "
                    f"positions/s={positions_seen / elapsed:,.0f}"
                )

            if (row_i + 1) % 50 == 0:
                gc.collect()

    for config in CONFIGS:
        name = config["name"]
        state = states[name]

        positive_score = np.concatenate(state["positive_score"])
        positive_count = np.concatenate(state["positive_count"])

        cv_rows.append(
            {
                "heldout_contig": heldout_contig,
                "config": name,
                "hard_fraction": config["hard_fraction"],
                "lambda_rank": config["lambda_rank"],
                "average_precision_5dp": ap_from_histograms(
                    state["positive_hist"],
                    state["total_hist"],
                ),
                "positive_spearman_raw": dense_rank_pearson(
                    positive_score,
                    positive_count,
                ),
                "positive_n": int(len(positive_count)),
            }
        )

cv_results = pd.DataFrame(cv_rows)
cv_results.to_csv(CV_RESULTS_PATH, index=False)

display(cv_results)
print("Saved:", CV_RESULTS_PATH)

================================================================================
EVAL FOLD 1/9 NC_064035.1
================================================================================
tiles=    1/18918 positions=         498 positions/s=23,827
tiles=  250/18918 positions=     374,670 positions/s=170,348
tiles=  500/18918 positions=     811,248 positions/s=183,401
tiles=  750/18918 positions=   1,209,988 positions/s=182,576
tiles= 1000/18918 positions=   1,606,742 positions/s=181,249
tiles= 1250/18918 positions=   2,025,652 positions/s=179,053
tiles= 1500/18918 positions=   2,447,804 positions/s=179,082
tiles= 1750/18918 positions=   2,875,410 positions/s=181,301
tiles= 2000/18918 positions=   3,276,578 positions/s=181,835
tiles= 2250/18918 positions=   3,727,040 positions/s=184,285
tiles= 2500/18918 positions=   4,184,270 positions/s=186,300
tiles= 2750/18918 positions=   4,626,284 positions/s=186,984
tiles= 3000/18918 positions=   5,062,232 positions/s=187,243
tiles= 3250/18918 positions=   5,524,502 positions/s=188,354
tiles= 3500/18918 positions=   5,960,950 positions/s=188,929
tiles= 3750/18918 positions=   6,421,794 positions/s=190,176
tiles= 4000/18918 positions=   6,859,048 positions/s=190,632
tiles= 4250/18918 positions=   7,299,348 positions/s=191,270
tiles= 4500/18918 positions=   7,756,778 positions/s=192,116
tiles= 4750/18918 positions=   8,210,538 positions/s=192,208
tiles= 5000/18918 positions=   8,656,002 positions/s=192,075
tiles= 5250/18918 positions=   9,101,054 positions/s=191,398
tiles= 5500/18918 positions=   9,573,816 positions/s=191,145
tiles= 5750/18918 positions=  10,015,794 positions/s=190,639
tiles= 6000/18918 positions=  10,465,638 positions/s=190,176
tiles= 6250/18918 positions=  10,912,152 positions/s=189,996
tiles= 6500/18918 positions=  11,333,008 positions/s=189,804
tiles= 6750/18918 positions=  11,771,484 positions/s=189,994
tiles= 7000/18918 positions=  12,200,608 positions/s=190,040
tiles= 7250/18918 positions=  12,659,838 positions/s=190,394
tiles= 7500/18918 positions=  13,098,322 positions/s=190,562
tiles= 7750/18918 positions=  13,534,950 positions/s=190,525
tiles= 8000/18918 positions=  13,994,822 positions/s=190,316
tiles= 8250/18918 positions=  14,462,576 positions/s=190,485
tiles= 8500/18918 positions=  14,901,088 positions/s=190,637
tiles= 8750/18918 positions=  15,365,308 positions/s=190,980
tiles= 9000/18918 positions=  15,810,964 positions/s=191,174
tiles= 9250/18918 positions=  16,250,422 positions/s=191,303
tiles= 9500/18918 positions=  16,695,200 positions/s=191,506
tiles= 9750/18918 positions=  17,137,850 positions/s=191,634
tiles=10000/18918 positions=  17,603,050 positions/s=191,989
tiles=10250/18918 positions=  18,053,340 positions/s=192,211
tiles=10500/18918 positions=  18,516,046 positions/s=192,440
tiles=10750/18918 positions=  18,972,510 positions/s=192,685
tiles=11000/18918 positions=  19,394,816 positions/s=192,369
tiles=11250/18918 positions=  19,837,696 positions/s=192,057
tiles=11500/18918 positions=  20,271,614 positions/s=191,871
tiles=11750/18918 positions=  20,681,734 positions/s=191,715
tiles=12000/18918 positions=  21,114,720 positions/s=191,732
tiles=12250/18918 positions=  21,567,178 positions/s=191,900
tiles=12500/18918 positions=  22,029,588 positions/s=192,110
tiles=12750/18918 positions=  22,496,296 positions/s=192,343
tiles=13000/18918 positions=  22,952,444 positions/s=192,499
tiles=13250/18918 positions=  23,405,132 positions/s=192,631
tiles=13500/18918 positions=  23,857,290 positions/s=192,703
tiles=13750/18918 positions=  24,245,722 positions/s=192,410
tiles=14000/18918 positions=  24,704,222 positions/s=192,558
tiles=14250/18918 positions=  25,164,024 positions/s=192,668
tiles=14500/18918 positions=  25,624,020 positions/s=192,622
tiles=14750/18918 positions=  26,082,418 positions/s=192,610
tiles=15000/18918 positions=  26,528,506 positions/s=192,730
tiles=15250/18918 positions=  26,974,386 positions/s=192,790
tiles=15500/18918 positions=  27,411,642 positions/s=192,831
tiles=15750/18918 positions=  27,853,676 positions/s=192,877
tiles=16000/18918 positions=  28,306,126 positions/s=193,003
tiles=16250/18918 positions=  28,769,036 positions/s=193,202
tiles=16500/18918 positions=  29,227,506 positions/s=193,365
tiles=16750/18918 positions=  29,695,424 positions/s=193,530
tiles=17000/18918 positions=  30,170,706 positions/s=193,765
tiles=17250/18918 positions=  30,600,446 positions/s=193,715
tiles=17500/18918 positions=  31,017,264 positions/s=193,595
tiles=17750/18918 positions=  31,454,206 positions/s=193,379
tiles=18000/18918 positions=  31,921,728 positions/s=193,315
tiles=18250/18918 positions=  32,348,840 positions/s=193,017
tiles=18500/18918 positions=  32,745,366 positions/s=192,779
tiles=18750/18918 positions=  33,168,042 positions/s=192,729
tiles=18918/18918 positions=  33,456,756 positions/s=192,661

================================================================================
EVAL FOLD 2/9 NC_064036.1
================================================================================
tiles=    1/17838 positions=         522 positions/s=33,272
tiles=  250/17838 positions=     290,226 positions/s=143,935
tiles=  500/17838 positions=     658,252 positions/s=157,198
tiles=  750/17838 positions=   1,071,848 positions/s=167,675
tiles= 1000/17838 positions=   1,493,048 positions/s=173,454
tiles= 1250/17838 positions=   1,924,276 positions/s=177,405
tiles= 1500/17838 positions=   2,368,740 positions/s=181,302
tiles= 1750/17838 positions=   2,817,784 positions/s=184,282
tiles= 2000/17838 positions=   3,259,184 positions/s=184,877
tiles= 2250/17838 positions=   3,704,732 positions/s=184,567
tiles= 2500/17838 positions=   4,158,236 positions/s=185,366
tiles= 2750/17838 positions=   4,602,230 positions/s=186,693
tiles= 3000/17838 positions=   5,030,634 positions/s=187,188
tiles= 3250/17838 positions=   5,469,770 positions/s=187,853
tiles= 3500/17838 positions=   5,919,934 positions/s=188,739
tiles= 3750/17838 positions=   6,369,194 positions/s=189,399
tiles= 4000/17838 positions=   6,814,518 positions/s=190,175
tiles= 4250/17838 positions=   7,264,772 positions/s=190,819
tiles= 4500/17838 positions=   7,740,340 positions/s=192,022
tiles= 4750/17838 positions=   8,208,088 positions/s=193,056
tiles= 5000/17838 positions=   8,659,072 positions/s=193,486
tiles= 5250/17838 positions=   9,123,928 positions/s=193,927
tiles= 5500/17838 positions=   9,584,078 positions/s=193,661
tiles= 5750/17838 positions=  10,043,302 positions/s=193,508
tiles= 6000/17838 positions=  10,492,068 positions/s=193,868
tiles= 6250/17838 positions=  10,949,978 positions/s=194,313
tiles= 6500/17838 positions=  11,409,988 positions/s=194,760
tiles= 6750/17838 positions=  11,874,476 positions/s=195,113
tiles= 7000/17838 positions=  12,328,214 positions/s=195,337
tiles= 7250/17838 positions=  12,771,810 positions/s=195,344
tiles= 7500/17838 positions=  13,233,372 positions/s=195,688
tiles= 7750/17838 positions=  13,690,638 positions/s=195,997
tiles= 8000/17838 positions=  14,144,298 positions/s=196,197
tiles= 8250/17838 positions=  14,576,606 positions/s=196,009
tiles= 8500/17838 positions=  14,995,684 positions/s=195,794
tiles= 8750/17838 positions=  15,458,776 positions/s=195,651
tiles= 9000/17838 positions=  15,891,820 positions/s=195,203
tiles= 9250/17838 positions=  16,349,444 positions/s=195,235
tiles= 9500/17838 positions=  16,791,944 positions/s=195,309
tiles= 9750/17838 positions=  17,234,298 positions/s=195,296
tiles=10000/17838 positions=  17,671,748 positions/s=195,258
tiles=10250/17838 positions=  18,144,822 positions/s=195,566
tiles=10500/17838 positions=  18,611,424 positions/s=195,792
tiles=10750/17838 positions=  19,075,824 positions/s=196,011
tiles=11000/17838 positions=  19,532,002 positions/s=196,162
tiles=11250/17838 positions=  20,004,360 positions/s=196,438
tiles=11500/17838 positions=  20,474,964 positions/s=196,695
tiles=11750/17838 positions=  20,922,280 positions/s=196,746
tiles=12000/17838 positions=  21,355,252 positions/s=196,382
tiles=12250/17838 positions=  21,814,644 positions/s=196,229
tiles=12500/17838 positions=  22,250,692 positions/s=196,012
tiles=12750/17838 positions=  22,694,324 positions/s=196,042
tiles=13000/17838 positions=  23,125,742 positions/s=195,986
tiles=13250/17838 positions=  23,570,502 positions/s=195,961
tiles=13500/17838 positions=  24,022,528 positions/s=195,793
tiles=13750/17838 positions=  24,466,866 positions/s=195,829
tiles=14000/17838 positions=  24,928,326 positions/s=195,966
tiles=14250/17838 positions=  25,356,832 positions/s=195,910
tiles=14500/17838 positions=  25,797,112 positions/s=195,915
tiles=14750/17838 positions=  26,254,272 positions/s=196,039
tiles=15000/17838 positions=  26,684,764 positions/s=195,900
tiles=15250/17838 positions=  27,115,956 positions/s=195,640
tiles=15500/17838 positions=  27,560,658 positions/s=195,458
tiles=15750/17838 positions=  28,010,830 positions/s=195,518
tiles=16000/17838 positions=  28,439,284 positions/s=195,480
tiles=16250/17838 positions=  28,890,416 positions/s=195,468
tiles=16500/17838 positions=  29,290,714 positions/s=195,230
tiles=16750/17838 positions=  29,716,026 positions/s=195,112
tiles=17000/17838 positions=  30,149,026 positions/s=195,082
tiles=17250/17838 positions=  30,615,562 positions/s=195,225
tiles=17500/17838 positions=  31,033,906 positions/s=195,113
tiles=17750/17838 positions=  31,460,060 positions/s=195,040
tiles=17838/17838 positions=  31,610,378 positions/s=195,005

================================================================================
EVAL FOLD 3/9 NC_064038.1
================================================================================
tiles=    1/14653 positions=       1,924 positions/s=166,778
tiles=  250/14653 positions=     376,256 positions/s=182,408
tiles=  500/14653 positions=     723,634 positions/s=172,286
tiles=  750/14653 positions=   1,083,776 positions/s=163,895
tiles= 1000/14653 positions=   1,485,444 positions/s=164,213
tiles= 1250/14653 positions=   1,868,366 positions/s=165,719
tiles= 1500/14653 positions=   2,224,238 positions/s=165,739
tiles= 1750/14653 positions=   2,597,368 positions/s=166,485
tiles= 2000/14653 positions=   3,004,448 positions/s=168,680
tiles= 2250/14653 positions=   3,442,344 positions/s=171,676
tiles= 2500/14653 positions=   3,874,686 positions/s=173,926
tiles= 2750/14653 positions=   4,312,064 positions/s=175,968
tiles= 3000/14653 positions=   4,742,870 positions/s=177,379
tiles= 3250/14653 positions=   5,198,618 positions/s=179,288
tiles= 3500/14653 positions=   5,628,044 positions/s=180,396
tiles= 3750/14653 positions=   6,065,334 positions/s=181,660
tiles= 4000/14653 positions=   6,482,838 positions/s=181,239
tiles= 4250/14653 positions=   6,937,162 positions/s=181,717
tiles= 4500/14653 positions=   7,388,266 positions/s=182,498
tiles= 4750/14653 positions=   7,848,958 positions/s=183,751
tiles= 5000/14653 positions=   8,304,512 positions/s=184,665
tiles= 5250/14653 positions=   8,746,442 positions/s=185,337
tiles= 5500/14653 positions=   9,172,930 positions/s=185,692
tiles= 5750/14653 positions=   9,581,350 positions/s=185,783
tiles= 6000/14653 positions=  10,017,158 positions/s=186,300
tiles= 6250/14653 positions=  10,470,138 positions/s=186,858
tiles= 6500/14653 positions=  10,918,800 positions/s=187,346
tiles= 6750/14653 positions=  11,339,394 positions/s=187,407
tiles= 7000/14653 positions=  11,778,260 positions/s=187,756
tiles= 7250/14653 positions=  12,241,502 positions/s=188,083
tiles= 7500/14653 positions=  12,687,192 positions/s=187,985
tiles= 7750/14653 positions=  13,149,180 positions/s=188,051
tiles= 8000/14653 positions=  13,606,068 positions/s=188,543
tiles= 8250/14653 positions=  14,030,156 positions/s=188,577
tiles= 8500/14653 positions=  14,467,532 positions/s=188,827
tiles= 8750/14653 positions=  14,900,526 positions/s=189,021
tiles= 9000/14653 positions=  15,354,906 positions/s=189,458
tiles= 9250/14653 positions=  15,798,274 positions/s=189,763
tiles= 9500/14653 positions=  16,225,860 positions/s=189,867
tiles= 9750/14653 positions=  16,684,644 positions/s=190,233
tiles=10000/14653 positions=  17,134,178 positions/s=190,468
tiles=10250/14653 positions=  17,602,928 positions/s=190,900
tiles=10500/14653 positions=  18,033,188 positions/s=191,034
tiles=10750/14653 positions=  18,481,866 positions/s=190,902
tiles=11000/14653 positions=  18,914,024 positions/s=190,580
tiles=11250/14653 positions=  19,337,884 positions/s=190,511
tiles=11500/14653 positions=  19,754,770 positions/s=190,455
tiles=11750/14653 positions=  20,204,480 positions/s=190,195
tiles=12000/14653 positions=  20,669,416 positions/s=190,402
tiles=12250/14653 positions=  21,123,804 positions/s=190,673
tiles=12500/14653 positions=  21,575,752 positions/s=190,736
tiles=12750/14653 positions=  22,032,090 positions/s=190,417
tiles=13000/14653 positions=  22,502,864 positions/s=190,402
tiles=13250/14653 positions=  22,961,676 positions/s=190,504
tiles=13500/14653 positions=  23,397,242 positions/s=190,556
tiles=13750/14653 positions=  23,812,260 positions/s=190,424
tiles=14000/14653 positions=  24,186,568 positions/s=189,883
tiles=14250/14653 positions=  24,560,158 positions/s=189,357
tiles=14500/14653 positions=  24,961,348 positions/s=189,226
tiles=14653/14653 positions=  25,217,952 positions/s=189,067

================================================================================
EVAL FOLD 4/9 NC_064039.1
================================================================================
tiles=    1/15499 positions=       1,984 positions/s=202,420
tiles=  250/15499 positions=     404,486 positions/s=181,395
tiles=  500/15499 positions=     832,522 positions/s=183,050
tiles=  750/15499 positions=   1,247,798 positions/s=184,858
tiles= 1000/15499 positions=   1,663,744 positions/s=186,172
tiles= 1250/15499 positions=   2,097,484 positions/s=187,938
tiles= 1500/15499 positions=   2,512,426 positions/s=187,824
tiles= 1750/15499 positions=   2,948,458 positions/s=189,194
tiles= 2000/15499 positions=   3,382,242 positions/s=190,093
tiles= 2250/15499 positions=   3,835,384 positions/s=191,388
tiles= 2500/15499 positions=   4,308,238 positions/s=192,298
tiles= 2750/15499 positions=   4,760,962 positions/s=191,899
tiles= 3000/15499 positions=   5,223,702 positions/s=192,127
tiles= 3250/15499 positions=   5,685,906 positions/s=193,341
tiles= 3500/15499 positions=   6,143,712 positions/s=194,173
tiles= 3750/15499 positions=   6,602,750 positions/s=194,980
tiles= 4000/15499 positions=   7,074,946 positions/s=195,757
tiles= 4250/15499 positions=   7,524,316 positions/s=196,075
tiles= 4500/15499 positions=   7,972,712 positions/s=196,201
tiles= 4750/15499 positions=   8,432,164 positions/s=196,739
tiles= 5000/15499 positions=   8,881,218 positions/s=196,991
tiles= 5250/15499 positions=   9,322,292 positions/s=197,014
tiles= 5500/15499 positions=   9,779,192 positions/s=197,358
tiles= 5750/15499 positions=  10,219,568 positions/s=196,642
tiles= 6000/15499 positions=  10,677,314 positions/s=196,173
tiles= 6250/15499 positions=  11,140,818 positions/s=196,258
tiles= 6500/15499 positions=  11,598,278 positions/s=196,693
tiles= 6750/15499 positions=  12,043,044 positions/s=196,772
tiles= 7000/15499 positions=  12,492,466 positions/s=196,891
tiles= 7250/15499 positions=  12,954,938 positions/s=197,153
tiles= 7500/15499 positions=  13,399,554 positions/s=197,055
tiles= 7750/15499 positions=  13,833,942 positions/s=197,011
tiles= 8000/15499 positions=  14,275,884 positions/s=197,091
tiles= 8250/15499 positions=  14,712,570 positions/s=197,018
tiles= 8500/15499 positions=  15,153,592 positions/s=196,900
tiles= 8750/15499 positions=  15,625,350 positions/s=197,207
tiles= 9000/15499 positions=  16,087,546 positions/s=197,104
tiles= 9250/15499 positions=  16,561,368 positions/s=196,934
tiles= 9500/15499 positions=  17,022,720 positions/s=196,842
tiles= 9750/15499 positions=  17,458,938 positions/s=196,788
tiles=10000/15499 positions=  17,920,928 positions/s=196,923
tiles=10250/15499 positions=  18,364,190 positions/s=197,008
tiles=10500/15499 positions=  18,809,722 positions/s=197,062
tiles=10750/15499 positions=  19,281,654 positions/s=197,262
tiles=11000/15499 positions=  19,750,882 positions/s=197,469
tiles=11250/15499 positions=  20,185,028 positions/s=197,354
tiles=11500/15499 positions=  20,637,176 positions/s=197,440
tiles=11750/15499 positions=  21,089,956 positions/s=197,503
tiles=12000/15499 positions=  21,546,540 positions/s=197,561
tiles=12250/15499 positions=  21,997,686 positions/s=197,529
tiles=12500/15499 positions=  22,447,784 positions/s=197,253
tiles=12750/15499 positions=  22,879,816 positions/s=196,863
tiles=13000/15499 positions=  23,329,474 positions/s=196,919
tiles=13250/15499 positions=  23,777,500 positions/s=197,006
tiles=13500/15499 positions=  24,232,814 positions/s=197,137
tiles=13750/15499 positions=  24,692,492 positions/s=197,230
tiles=14000/15499 positions=  25,139,360 positions/s=197,182
tiles=14250/15499 positions=  25,580,466 positions/s=197,186
tiles=14500/15499 positions=  25,986,150 positions/s=196,994
tiles=14750/15499 positions=  26,424,574 positions/s=196,974
tiles=15000/15499 positions=  26,859,490 positions/s=196,910
tiles=15250/15499 positions=  27,301,012 positions/s=196,935
tiles=15499/15499 positions=  27,686,596 positions/s=196,555

================================================================================
EVAL FOLD 5/9 NC_064040.1
================================================================================
tiles=    1/14812 positions=         668 positions/s=64,784
tiles=  250/14812 positions=     325,388 positions/s=142,923
tiles=  500/14812 positions=     705,904 positions/s=151,158
tiles=  750/14812 positions=   1,098,550 positions/s=160,220
tiles= 1000/14812 positions=   1,522,084 positions/s=168,154
tiles= 1250/14812 positions=   1,982,120 positions/s=174,888
tiles= 1500/14812 positions=   2,445,854 positions/s=180,251
tiles= 1750/14812 positions=   2,858,462 positions/s=181,495
tiles= 2000/14812 positions=   3,279,464 positions/s=182,191
tiles= 2250/14812 positions=   3,712,326 positions/s=183,305
tiles= 2500/14812 positions=   4,156,236 positions/s=184,955
tiles= 2750/14812 positions=   4,592,444 positions/s=185,960
tiles= 3000/14812 positions=   5,008,944 positions/s=186,079
tiles= 3250/14812 positions=   5,448,316 positions/s=186,830
tiles= 3500/14812 positions=   5,876,394 positions/s=185,768
tiles= 3750/14812 positions=   6,281,820 positions/s=184,491
tiles= 4000/14812 positions=   6,743,426 positions/s=185,683
tiles= 4250/14812 positions=   7,225,346 positions/s=187,373
tiles= 4500/14812 positions=   7,679,720 positions/s=187,464
tiles= 4750/14812 positions=   8,119,012 positions/s=186,549
tiles= 5000/14812 positions=   8,576,236 positions/s=186,161
tiles= 5250/14812 positions=   9,062,680 positions/s=187,264
tiles= 5500/14812 positions=   9,521,286 positions/s=187,040
tiles= 5750/14812 positions=   9,992,934 positions/s=187,193
tiles= 6000/14812 positions=  10,435,792 positions/s=187,825
tiles= 6250/14812 positions=  10,900,488 positions/s=188,263
tiles= 6500/14812 positions=  11,364,084 positions/s=188,389
tiles= 6750/14812 positions=  11,822,472 positions/s=188,393
tiles= 7000/14812 positions=  12,257,852 positions/s=188,401
tiles= 7250/14812 positions=  12,701,364 positions/s=188,852
tiles= 7500/14812 positions=  13,123,076 positions/s=188,833
tiles= 7750/14812 positions=  13,565,902 positions/s=188,702
tiles= 8000/14812 positions=  13,994,606 positions/s=188,534
tiles= 8250/14812 positions=  14,433,414 positions/s=188,289
tiles= 8500/14812 positions=  14,872,470 positions/s=188,251
tiles= 8750/14812 positions=  15,333,246 positions/s=188,722
tiles= 9000/14812 positions=  15,761,110 positions/s=188,774
tiles= 9250/14812 positions=  16,226,370 positions/s=189,161
tiles= 9500/14812 positions=  16,660,374 positions/s=189,325

,heldout_contig,config,hard_fraction,lambda_rank,average_precision_5dp,positive_spearman_raw,positive_n
0,NC_064035.1,hard25_lambda0p0,0.25,0.0,0.011681,0.116434,30987
1,NC_064035.1,hard25_lambda0p1,0.25,0.1,0.007600,0.085000,30987
2,NC_064035.1,hard25_lambda0p3,0.25,0.3,0.004517,0.044979,30987
3,NC_064035.1,hard25_lambda1p0,0.25,1.0,0.001686,-0.050061,30987
4,NC_064035.1,hard50_lambda0p0,0.50,0.0,0.003047,0.007560,30987
...,...,...,...,...,...,...,...
67,NC_064048.1,hard25_lambda1p0,0.25,1.0,0.001102,-0.044106,10888
68,NC_064048.1,hard50_lambda0p0,0.50,0.0,0.001990,0.005764,10888
69,NC_064048.1,hard50_lambda0p1,0.50,0.1,0.001615,-0.009867,10888
70,NC_064048.1,hard50_lambda0p3,0.50,0.3,0.001114,-0.036378,10888
71,NC_064048.1,hard50_lambda1p0,0.50,1.0,0.000674,-0.080412,10888

Saved: D:\Projects\EPIC\EPIC\artifacts\experiments\CNN_EXP037_FROZEN_WIDTH64_HARDFP_RERANKER\run_001\cross_contig_cv.csv

In [12]:
cv_summary = (
    cv_results
    .groupby(
        ["config", "hard_fraction", "lambda_rank"],
        as_index=False,
    )
    .agg(
        mean_AP=("average_precision_5dp", "mean"),
        min_AP=("average_precision_5dp", "min"),
        max_AP=("average_precision_5dp", "max"),
        mean_positive_spearman=("positive_spearman_raw", "mean"),
    )
    .sort_values(
        ["mean_AP", "min_AP"],
        ascending=False,
    )
    .reset_index(drop=True)
)

display(cv_summary)

BEST_CONFIG_NAME = str(cv_summary.iloc[0]["config"])

BEST_CONFIG = next(
    config
    for config in CONFIGS
    if config["name"] == BEST_CONFIG_NAME
)

CV_SUMMARY_PATH = RUN_DIR / "cross_contig_cv_summary.csv"
cv_summary.to_csv(CV_SUMMARY_PATH, index=False)

print("SELECTED:", BEST_CONFIG)
print("Saved:", CV_SUMMARY_PATH)

,config,hard_fraction,lambda_rank,mean_AP,min_AP,max_AP,mean_positive_spearman
0,hard25_lambda0p0,0.25,0.0,0.009860,0.007784,0.011681,0.110448
1,hard25_lambda0p1,0.25,0.1,0.006264,0.004914,0.007600,0.080463
2,hard25_lambda0p3,0.25,0.3,0.003524,0.002686,0.004517,0.035786
3,hard50_lambda0p0,0.50,0.0,0.002464,0.001913,0.003047,0.006119
4,hard50_lambda0p1,0.50,0.1,0.002012,0.001428,0.002433,-0.011117
5,hard50_lambda0p3,0.50,0.3,0.001444,0.001099,0.001786,-0.044654
6,hard25_lambda1p0,0.25,1.0,0.001332,0.001031,0.001686,-0.054872
7,hard50_lambda1p0,0.50,1.0,0.000823,0.000618,0.001033,-0.098212

SELECTED: {'name': 'hard25_lambda0p0', 'hard_fraction': 0.25, 'lambda_rank': 0.0}
Saved: D:\Projects\EPIC\EPIC\artifacts\experiments\CNN_EXP037_FROZEN_WIDTH64_HARDFP_RERANKER\run_001\cross_contig_cv_summary.csv

## 4. Final head на всех 9 train-contigs

In [13]:
FINAL_HEAD = train_linear_head(
    train_pos_X=pos_X,
    train_random_X=random_X,
    train_hard_X=hard_X,
    hard_fraction=BEST_CONFIG["hard_fraction"],
    lambda_rank=BEST_CONFIG["lambda_rank"],
    seed=999_037,
)

FINAL_HEAD_PATH = RUN_DIR / "final_linear_presence_head.npz"

np.savez(
    FINAL_HEAD_PATH,
    w_raw=FINAL_HEAD["w_raw"],
    b_raw=np.array([FINAL_HEAD["b_raw"]], dtype=np.float32),
    hard_fraction=np.array(
        [BEST_CONFIG["hard_fraction"]],
        dtype=np.float32,
    ),
    lambda_rank=np.array(
        [BEST_CONFIG["lambda_rank"]],
        dtype=np.float32,
    ),
)

print("Selected:", BEST_CONFIG)
print("Final head:", FINAL_HEAD_PATH)
print(
    {
        key: FINAL_HEAD[key]
        for key in ("n_pos", "n_neg", "n_hard", "n_random")
    }
)

Selected: {'name': 'hard25_lambda0p0', 'hard_fraction': 0.25, 'lambda_rank': 0.0}
Final head: D:\Projects\EPIC\EPIC\artifacts\experiments\CNN_EXP037_FROZEN_WIDTH64_HARDFP_RERANKER\run_001\final_linear_presence_head.npz
{'n_pos': 170443, 'n_neg': 681772, 'n_hard': 170443, 'n_random': 511329}

## 5. Один полный validation

Считаем:

- baseline WIDTH64 AP;
- reranker AP;
- AP по каждому validation-contig;
- baseline presence Spearman;
- reranker Spearman на positives;
- frozen intensity Spearman;
- top 1/5/10%;
- baseline HARD_FP cohort retention;
- LOW_TP recall как guardrail.

In [14]:
BUDGETS = (0.01, 0.05, 0.10)

VALIDATION_HARD_CANDIDATES_PER_TILE_STRAND = 4
VALIDATION_HARD_FP_KEEP = 20_000


def new_eval_state():
    return {
        "baseline_total_hist": np.zeros(
            SUBMISSION_LEVELS,
            dtype=np.int64,
        ),
        "baseline_positive_hist": np.zeros(
            SUBMISSION_LEVELS,
            dtype=np.int64,
        ),
        "rerank_total_hist": np.zeros(
            SUBMISSION_LEVELS,
            dtype=np.int64,
        ),
        "rerank_positive_hist": np.zeros(
            SUBMISSION_LEVELS,
            dtype=np.int64,
        ),
        "positive_baseline_score": [],
        "positive_rerank_score": [],
        "positive_intensity": [],
        "positive_count": [],
        "hard_candidate_baseline_score": [],
        "hard_candidate_rerank_score": [],
    }


def threshold_for_top_fraction(total_hist, fraction):
    total = int(total_hist.sum())
    target = int(math.ceil(fraction * total))

    desc = total_hist[::-1]
    cumulative = np.cumsum(desc, dtype=np.int64)

    idx = int(
        np.searchsorted(
            cumulative,
            target,
            side="left",
        )
    )

    bin_index = SUBMISSION_LEVELS - 1 - idx
    selected = int(cumulative[idx])

    return {
        "bin_index": int(bin_index),
        "threshold": float(bin_index / 100_000.0),
        "selected": selected,
        "selected_fraction": float(selected / total),
    }


def budget_stats(total_hist, positive_hist, fraction):
    threshold = threshold_for_top_fraction(
        total_hist,
        fraction,
    )

    b = threshold["bin_index"]

    selected = int(total_hist[b:].sum())
    tp = int(positive_hist[b:].sum())
    fp = selected - tp

    positives = int(positive_hist.sum())

    return {
        **threshold,
        "tp": tp,
        "fp": fp,
        "precision": float(tp / max(selected, 1)),
        "recall": float(tp / max(positives, 1)),
    }

In [15]:
segment_names = ["overall", *VALIDATION_CONTIGS]

eval_states = {
    segment: new_eval_state()
    for segment in segment_names
}

positions_seen = 0
started = time.perf_counter()

frozen_model.eval()

with torch.no_grad():
    for row_i in range(len(validation_tiles)):
        selected = validation_tiles.iloc[row_i:row_i + 1]
        contig = str(selected.iloc[0]["contig"])

        batch = validation_generator.make_batch(selected)

        features, old_logit, old_intensity = (
            extract_backbone_and_old_outputs(
                frozen_model,
                batch,
            )
        )

        baseline_probability = sigmoid_numpy(old_logit)

        rerank_probability = np.stack(
            [
                score_linear_raw(
                    features[orient_i],
                    FINAL_HEAD["w_raw"],
                    FINAL_HEAD["b_raw"],
                )
                for orient_i in range(features.shape[0])
            ],
            axis=0,
        )

        plus_count = (
            batch.count[0, 0, :]
            .numpy().astype(np.float32, copy=False)
        )
        minus_count_reverse = (
            batch.count[0, 1, :]
            .flip(-1)
            .numpy().astype(np.float32, copy=False)
        )

        plus_mask = (
            batch.mask[0, 0, :]
            .numpy().astype(bool, copy=False)
        )
        minus_mask_reverse = (
            batch.mask[0, 1, :]
            .flip(-1)
            .numpy().astype(bool, copy=False)
        )

        for orient_i, (count, mask) in enumerate(
            (
                (plus_count, plus_mask),
                (minus_count_reverse, minus_mask_reverse),
            )
        ):
            valid_index = np.flatnonzero(mask)

            valid_count = count[valid_index]
            positive = valid_count > 0

            baseline_score = baseline_probability[
                orient_i,
                valid_index,
            ]
            rerank_score = rerank_probability[
                orient_i,
                valid_index,
            ]
            intensity_score = old_intensity[
                orient_i,
                valid_index,
            ]

            baseline_bin = probability_bin_5dp(baseline_score)
            rerank_bin = probability_bin_5dp(rerank_score)

            for segment in ("overall", contig):
                state = eval_states[segment]

                update_histogram(
                    state["baseline_total_hist"],
                    baseline_bin,
                )
                update_histogram(
                    state["rerank_total_hist"],
                    rerank_bin,
                )

                if positive.any():
                    update_histogram(
                        state["baseline_positive_hist"],
                        baseline_bin[positive],
                    )
                    update_histogram(
                        state["rerank_positive_hist"],
                        rerank_bin[positive],
                    )

                    state["positive_baseline_score"].append(
                        baseline_score[positive].copy()
                    )
                    state["positive_rerank_score"].append(
                        rerank_score[positive].copy()
                    )
                    state["positive_intensity"].append(
                        intensity_score[positive].copy()
                    )
                    state["positive_count"].append(
                        valid_count[positive].copy()
                    )

            negative_index = np.flatnonzero(~positive)

            if len(negative_index):
                n_hard = min(
                    VALIDATION_HARD_CANDIDATES_PER_TILE_STRAND,
                    len(negative_index),
                )

                negative_baseline = baseline_score[negative_index]

                if len(negative_index) <= n_hard:
                    hard_local = negative_index
                else:
                    top = np.argpartition(
                        negative_baseline,
                        -n_hard,
                    )[-n_hard:]
                    hard_local = negative_index[top]

                for segment in ("overall", contig):
                    eval_states[segment][
                        "hard_candidate_baseline_score"
                    ].append(
                        baseline_score[hard_local].copy()
                    )

                    eval_states[segment][
                        "hard_candidate_rerank_score"
                    ].append(
                        rerank_score[hard_local].copy()
                    )

            positions_seen += int(mask.sum())

        del (
            batch,
            selected,
            features,
            old_logit,
            old_intensity,
            baseline_probability,
            rerank_probability,
            plus_count,
            minus_count_reverse,
            plus_mask,
            minus_mask_reverse,
        )

        if (
            row_i == 0
            or (row_i + 1) % 100 == 0
            or row_i + 1 == len(validation_tiles)
        ):
            elapsed = time.perf_counter() - started
            print(
                f"tiles={row_i + 1:>6}/{len(validation_tiles)} "
                f"positions={positions_seen:>13,} "
                f"positions/s={positions_seen / elapsed:,.0f}"
            )

        if (row_i + 1) % 25 == 0:
            gc.collect()

print("FULL VALIDATION FINISHED")

tiles=     1/47743 positions=          210 positions/s=26,910
tiles=   100/47743 positions=      125,828 positions/s=154,112
tiles=   200/47743 positions=      269,398 positions/s=154,921
tiles=   300/47743 positions=      403,094 positions/s=153,443
tiles=   400/47743 positions=      552,594 positions/s=156,183
tiles=   500/47743 positions=      708,204 positions/s=159,064
tiles=   600/47743 positions=      871,458 positions/s=162,565
tiles=   700/47743 positions=    1,020,090 positions/s=162,692
tiles=   800/47743 positions=    1,185,336 positions/s=165,083
tiles=   900/47743 positions=    1,346,300 positions/s=166,522
tiles=  1000/47743 positions=    1,519,462 positions/s=168,995
tiles=  1100/47743 positions=    1,700,978 positions/s=171,877
tiles=  1200/47743 positions=    1,853,300 positions/s=171,609
tiles=  1300/47743 positions=    2,017,896 positions/s=172,381
tiles=  1400/47743 positions=    2,193,246 positions/s=172,601
tiles=  1500/47743 positions=    2,381,142 positions/s=173,433
tiles=  1600/47743 positions=    2,551,896 positions/s=173,138
tiles=  1700/47743 positions=    2,735,154 positions/s=173,499
tiles=  1800/47743 positions=    2,908,724 positions/s=173,520
tiles=  1900/47743 positions=    3,093,954 positions/s=174,711
tiles=  2000/47743 positions=    3,270,676 positions/s=175,659
tiles=  2100/47743 positions=    3,440,356 positions/s=176,238
tiles=  2200/47743 positions=    3,601,668 positions/s=176,359
tiles=  2300/47743 positions=    3,773,708 positions/s=176,878
tiles=  2400/47743 positions=    3,954,690 positions/s=177,523
tiles=  2500/47743 positions=    4,124,072 positions/s=177,505
tiles=  2600/47743 positions=    4,314,720 positions/s=178,577
tiles=  2700/47743 positions=    4,499,834 positions/s=179,091
tiles=  2800/47743 positions=    4,687,412 positions/s=179,993
tiles=  2900/47743 positions=    4,869,112 positions/s=180,648
tiles=  3000/47743 positions=    5,044,192 positions/s=181,006
tiles=  3100/47743 positions=    5,227,018 positions/s=181,621
tiles=  3200/47743 positions=    5,417,186 positions/s=182,394
tiles=  3300/47743 positions=    5,601,634 positions/s=182,984
tiles=  3400/47743 positions=    5,788,068 positions/s=183,579
tiles=  3500/47743 positions=    5,964,294 positions/s=183,776
tiles=  3600/47743 positions=    6,151,408 positions/s=184,149
tiles=  3700/47743 positions=    6,328,330 positions/s=183,836
tiles=  3800/47743 positions=    6,511,894 positions/s=184,265
tiles=  3900/47743 positions=    6,683,476 positions/s=184,264
tiles=  4000/47743 positions=    6,861,742 positions/s=184,483
tiles=  4100/47743 positions=    7,040,760 positions/s=184,749
tiles=  4200/47743 positions=    7,223,104 positions/s=185,066
tiles=  4300/47743 positions=    7,403,458 positions/s=185,329
tiles=  4400/47743 positions=    7,591,562 positions/s=185,740
tiles=  4500/47743 positions=    7,765,704 positions/s=185,853
tiles=  4600/47743 positions=    7,952,580 positions/s=185,925
tiles=  4700/47743 positions=    8,144,412 positions/s=186,083
tiles=  4800/47743 positions=    8,315,836 positions/s=185,852
tiles=  4900/47743 positions=    8,499,598 positions/s=185,887
tiles=  5000/47743 positions=    8,686,708 positions/s=185,988
tiles=  5100/47743 positions=    8,869,760 positions/s=186,071
tiles=  5200/47743 positions=    9,053,752 positions/s=186,357
tiles=  5300/47743 positions=    9,234,498 positions/s=186,583
tiles=  5400/47743 positions=    9,418,676 positions/s=186,774
tiles=  5500/47743 positions=    9,601,468 positions/s=186,875
tiles=  5600/47743 positions=    9,787,520 positions/s=187,103
tiles=  5700/47743 positions=    9,961,466 positions/s=187,144
tiles=  5800/47743 positions=   10,121,628 positions/s=186,867
tiles=  5900/47743 positions=   10,303,464 positions/s=187,025
tiles=  6000/47743 positions=   10,486,418 positions/s=187,229
tiles=  6100/47743 positions=   10,659,222 positions/s=187,255
tiles=  6200/47743 positions=   10,850,162 positions/s=187,583
tiles=  6300/47743 positions=   11,034,092 positions/s=187,801
tiles=  6400/47743 positions=   11,211,346 positions/s=187,910
tiles=  6500/47743 positions=   11,404,050 positions/s=188,247
tiles=  6600/47743 positions=   11,595,690 positions/s=188,551
tiles=  6700/47743 positions=   11,768,214 positions/s=188,563
tiles=  6800/47743 positions=   11,957,186 positions/s=188,798
tiles=  6900/47743 positions=   12,132,994 positions/s=188,806
tiles=  7000/47743 positions=   12,320,412 positions/s=189,029
tiles=  7100/47743 positions=   12,504,026 positions/s=189,141
tiles=  7200/47743 positions=   12,692,176 positions/s=189,330
tiles=  7300/47743 positions=   12,883,724 positions/s=189,573
tiles=  7400/47743 positions=   13,073,512 positions/s=189,783
tiles=  7500/47743 positions=   13,254,998 positions/s=189,861
tiles=  7600/47743 positions=   13,446,690 positions/s=190,065
tiles=  7700/47743 positions=   13,626,572 positions/s=190,146
tiles=  7800/47743 positions=   13,811,846 positions/s=190,225
tiles=  7900/47743 positions=   13,992,532 positions/s=190,061
tiles=  8000/47743 positions=   14,166,170 positions/s=189,838
tiles=  8100/47743 positions=   14,348,130 positions/s=189,763
tiles=  8200/47743 positions=   14,530,186 positions/s=189,709
tiles=  8300/47743 positions=   14,707,390 positions/s=189,603
tiles=  8400/47743 positions=   14,903,230 positions/s=189,815
tiles=  8500/47743 positions=   15,084,582 positions/s=189,925
tiles=  8600/47743 positions=   15,264,906 positions/s=190,004
tiles=  8700/47743 positions=   15,445,592 positions/s=190,073
tiles=  8800/47743 positions=   15,625,072 positions/s=190,085
tiles=  8900/47743 positions=   15,812,596 positions/s=190,228
tiles=  9000/47743 positions=   15,986,332 positions/s=190,196
tiles=  9100/47743 positions=   16,150,714 positions/s=190,075
tiles=  9200/47743 positions=   16,325,720 positions/s=190,059
tiles=  9300/47743 positions=   16,508,688 positions/s=190,101
tiles=  9400/47743 positions=   16,694,912 positions/s=190,231
tiles=  9500/47743 positions=   16,885,552 positions/s=190,392
tiles=  9600/47743 positions=   17,065,138 positions/s=190,455
tiles=  9700/47743 positions=   17,240,900 positions/s=190,470
tiles=  9800/47743 positions=   17,422,180 positions/s=190,526
tiles=  9900/47743 positions=   17,605,102 positions/s=190,585
tiles= 10000/47743 positions=   17,785,210 positions/s=190,650
tiles= 10100/47743 positions=   17,972,524 positions/s=190,768
tiles= 10200/47743 positions=   18,146,778 positions/s=190,756
tiles= 10300/47743 positions=   18,335,334 positions/s=190,901
tiles= 10400/47743 positions=   18,508,362 positions/s=190,891
tiles= 10500/47743 positions=   18,701,250 positions/s=191,066
tiles= 10600/47743 positions=   18,886,020 positions/s=191,162
tiles= 10700/47743 positions=   19,078,810 positions/s=191,339
tiles= 10800/47743 positions=   19,264,144 positions/s=191,442
tiles= 10900/47743 positions=   19,450,764 positions/s=191,529
tiles= 11000/47743 positions=   19,629,450 positions/s=191,500
tiles= 11100/47743 positions=   19,810,528 positions/s=191,323
tiles= 11200/47743 positions=   19,990,916 positions/s=191,194
tiles= 11300/47743 positions=   20,173,320 positions/s=191,124
tiles= 11400/47743 positions=   20,362,978 positions/s=191,114
tiles= 11500/47743 positions=   20,543,204 positions/s=191,023
tiles= 11600/47743 positions=   20,734,052 positions/s=191,148
tiles= 11700/47743 positions=   20,924,040 positions/s=191,263
tiles= 11800/47743 positions=   21,107,246 positions/s=191,324
tiles= 11900/47743 positions=   21,293,564 positions/s=191,313
tiles= 12000/47743 positions=   21,458,144 positions/s=191,097
tiles= 12100/47743 positions=   21,636,636 positions/s=191,000
tiles= 12200/47743 positions=   21,806,558 positions/s=190,827
tiles= 12300/47743 positions=   21,984,562 positions/s=190,732
tiles= 12400/47743 positions=   22,170,108 positions/s=190,659
tiles= 12500/47743 positions=   22,348,906 positions/s=190,672
tiles= 12600/47743 positions=   22,532,044 positions/s=190,717
tiles= 12700/47743 positions=   22,725,192 positions/s=190,839
tiles= 12800/47743 positions=   22,887,364 positions/s=190,693
tiles= 12900/47743 positions=   23,072,164 positions/s=190,775
tiles= 13000/47743 positions=   23,257,996 positions/s=190,850
tiles= 13100/47743 positions=   23,428,662 positions/s=190,804
tiles= 13200/47743 positions=   23,615,126 positions/s=190,893
tiles= 13300/47743 positions=   23,790,240 positions/s=190,868
tiles= 13400/47743 positions=   23,975,094 positions/s=190,932
tiles= 13500/47743 positions=   24,159,682 positions/s=191,003
tiles= 13600/47743 positions=   24,342,072 positions/s=191,048
tiles= 13700/47743 positions=   24,532,054 positions/s=191,134
tiles= 13800/47743 positions=   24,688,318 positions/s=190,978
tiles= 13900/47743 positions=   24,873,868 positions/s=191,054
tiles= 14000/47743 positions=   25,044,318 positions/s=190,996
tiles= 14100/47743 positions=   25,217,552 positions/s=190,970
tiles= 14200/47743 positions=   25,398,834 positions/s=190,884
tiles= 14300/47743 positions=   25,574,128 positions/s=190,776
tiles= 14400/47743 positions=   25,750,848 positions/s=190,680
tiles= 14500/47743 positions=   25,901,906 positions/s=190,373
tiles= 14600/47743 positions=   26,083,078 positions/s=190,238
tiles= 14700/47743 positions=   26,262,636 positions/s=190,218
tiles= 14800/47743 positions=   26,430,250 positions/s=190,140
tiles= 14900/47743 positions=   26,611,076 positions/s=190,156
tiles= 15000/47743 positions=   26,790,808 positions/s=190,161
tiles= 15100/47743 positions=   26,968,374 positions/s=190,159
tiles= 15200/47743 positions=   27,145,486 positions/s=190,158
tiles= 15300/47743 positions=   27,326,816 positions/s=190,185
tiles= 15400/47743 positions=   27,517,854 positions/s=190,262
tiles= 15500/47743 positions=   27,701,240 positions/s=190,291
tiles= 15600/47743 positions=   27,878,016 positions/s=190,283
tiles= 15700/47743 positions=   28,062,470 positions/s=190,324
tiles= 15800/47743 positions=   28,251,508 positions/s=190,393
tiles= 15900/47743 positions=   28,440,288 positions/s=190,467
tiles= 16000/47743 positions=   28,627,148 positions/s=190,539
tiles= 16100/47743 positions=   28,819,644 positions/s=190,638
tiles= 16200/47743 positions=   28,970,346 positions/s=190,452
tiles= 16300/47743 positions=   29,146,312 positions/s=190,449
tiles= 16400/47743 positions=   29,335,814 positions/s=190,527
tiles= 16500/47743 positions=   29,523,910 positions/s=190,590
tiles= 16600/47743 positions=   29,704,584 positions/s=190,616
tiles= 16700/47743 positions=   29,889,734 positions/s=190,660
tiles= 16800/47743 positions=   30,068,710 positions/s=190,678
tiles= 16900/47743 positions=   30,232,050 positions/s=190,598
tiles= 17000/47743 positions=   30,384,274 positions/s=190,428
tiles= 17100/47743 positions=   30,535,264 positions/s=190,258
tiles= 17200/47743 positions=   30,715,634 positions/s=190,276
tiles= 17300/47743 positions=   30,886,036 positions/s=190,228
tiles= 17400/47743 positions=   31,059,276 positions/s=190,124
tiles= 17500/47743 positions=   31,244,790 positions/s=190,085
tiles= 17600/47743 positions=   31,432,844 positions/s=190,069
tiles= 17700/47743 positions=   31,607,010 positions/s=189,972
tiles= 17800/47743 positions=   31,777,182 positions/s=189,861
tiles= 17900/47743 positions=   31,955,260 positions/s=189,819
tiles= 18000/47743 positions=   32,126,086 positions/s=189,784
tiles= 18100/47743 positions=   32,304,388 positions/s=189,797
tiles= 18200/47743 positions=   32,476,876 positions/s=189,770
tiles= 18300/47743 positions=   32,663,782 positions/s=189,821
tiles= 18400/47743 positions=   32,851,188 positions/s=189,885
tiles= 18500/47743 positions=   33,023,686 positions/s=189,840
tiles= 18600/47743 positions=   33,207,082 positions/s=189,843
tiles= 18700/47743 positions=   33,388,746 positions/s=189,850
tiles= 18800/47743 positions=   33,564,628 positions/s=189,799
tiles= 18900/47743 positions=   33,747,122 positions/s=189,822
tiles= 19000/47743 positions=   33,937,908 positions/s=189,902
tiles= 19100/47743 positions=   34,088,414 positions/s=189,755
tiles= 19200/47743 positions=   34,277,242 positions/s=189,821
tiles= 19300/47743 positions=   34,452,998 positions/s=189,808
tiles= 19400/47743 positions=   34,619,586 positions/s=189,750
tiles= 19500/47743 positions=   34,765,250 positions/s=189,592
tiles= 19600/47743 positions=   34,913,180 positions/s=189,440
tiles= 19700/47743 positions=   35,077,800 positions/s=189,364
tiles= 19800/47743 positions=   35,248,624 positions/s=189,307
tiles= 19900/47743 positions=   35,417,528 positions/s=189,262
tiles= 20000/47743 positions=   35,584,246 positions/s=189,208
tiles= 20100/47743 positions=   35,743,076 positions/s=189,110
tiles= 20200/47743 positions=   35,908,546 positions/s=189,036
tiles= 20300/47743 positions=   36,090,206 positions/s=189,062
tiles= 20400/47743 positions=   36,241,266 positions/s=188,941
tiles= 20500/47743 positions=   36,414,186 positions/s=188,890
tiles= 20600/47743 positions=   36,575,502 positions/s=188,730
tiles= 20700/47743 positions=   36,751,380 positions/s=188,654
tiles= 20800/47743 positions=   36,933,668 positions/s=188,618
tiles= 20900/47743 positions=   37,105,904 positions/s=188,495
tiles= 21000/47743 positions=   37,293,080 positions/s=188,349
tiles= 21100/47743 positions=   37,484,284 positions/s=188,357
tiles= 21200/47743 positions=   37,669,352 positions/s=188,354
tiles= 21300/47743 positions=   37,845,822 positions/s=188,312
tiles= 21400/47743 positions=   38,005,266 positions/s=188,168
tiles= 21500/47743 positions=   38,182,250 positions/s=188,140
tiles= 21600/47743 positions=   38,367,294 positions/s=188,172
tiles= 21700/47743 positions=   38,538,398 positions/s=188,101
tiles= 21800/47743 positions=   38,713,832 positions/s=188,106
tiles= 21900/47743 positions=   38,881,070 positions/s=188,075
tiles= 22000/47743 positions=   39,054,518 positions/s=188,078
tiles= 22100/47743 positions=   39,231,742 positions/s=188,090
tiles= 22200/47743 positions=   39,382,128 positions/s=187,980
tiles= 22300/47743 positions=   39,558,258 positions/s=187,998
tiles= 22400/47743 positions=   39,727,400 positions/s=187,981
tiles= 22500/47743 positions=   39,911,304 positions/s=188,014
tiles= 22600/47743 positions=   40,097,750 positions/s=188,069
tiles= 22700/47743 positions=   40,267,856 positions/s=188,059
tiles= 22800/47743 positions=   40,445,212 positions/s=188,062
tiles= 22900/47743 positions=   40,616,092 positions/s=188,053
tiles= 23000/47743 positions=   40,786,524 positions/s=188,026
tiles= 23100/47743 positions=   40,968,792 positions/s=188,055
tiles= 23200/47743 positions=   41,148,108 positions/s=188,041
tiles= 23300/47743 positions=   41,329,910 positions/s=187,991
tiles= 23400/47743 positions=   41,516,210 positions/s=188,018
tiles= 23500/47743 positions=   41,695,364 positions/s=188,042
tiles= 23600/47743 positions=   41,870,574 positions/s=188,010
tiles= 23700/47743 positions=   42,041,788 positions/s=187,942
tiles= 23800/47743 positions=   42,225,160 positions/s=187,985
tiles= 23900/47743 positions=   42,396,522 positions/s=187,964
tiles= 24000/47743 positions=   42,571,942 positions/s=187,973
tiles= 24100/47743 positions=   42,750,224 positions/s=187,992
tiles= 24200/47743 positions=   42,934,092 positions/s=188,033
tiles= 24300/47743 positions=   43,119,856 positions/s=188,086
tiles= 24400/47743 positions=   43,279,204 positions/s=188,022
tiles= 24500/47743 positions=   43,462,310 positions/s=188,072
tiles= 24600/47743 positions=   43,638,514 positions/s=188,026
tiles= 24700/47743 positions=   43,815,976 positions/s=187,978
tiles= 24800/47743 positions=   43,997,800 positions/s=187,976
tiles= 24900/47743 positions=   44,176,440 positions/s=187,938
tiles= 25000/47743 positions=   44,353,956 positions/s=187,928
tiles= 25100/47743 positions=   44,528,858 positions/s=187,928
tiles= 25200/47743 positions=   44,711,716 positions/s=187,971
tiles= 25300/47743 positions=   44,886,564 positions/s=187,972
tiles= 25400/47743 positions=   45,069,572 positions/s=187,968
tiles= 25500/47743 positions=   45,249,102 positions/s=187,931
tiles= 25600/47743 positions=   45,425,826 positions/s=187,894
tiles= 25700/47743 positions=   45,612,440 positions/s=187,909
tiles= 25800/47743 positions=   45,789,812 positions/s=187,861
tiles= 25900/47743 positions=   45,969,950 positions/s=187,838
tiles= 26000/47743 positions=   46,125,962 positions/s=187,698
tiles= 26100/47743 positions=   46,304,598 positions/s=187,652
tiles= 26200/47743 positions=   46,490,684 positions/s=187,677
tiles= 26300/47743 positions=   46,671,784 positions/s=187,626
tiles= 26400/47743 positions=   46,851,854 positions/s=187,511
tiles= 26500/47743 positions=   47,034,314 positions/s=187,424
tiles= 26600/47743 positions=   47,217,472 positions/s=187,329
tiles= 26700/47743 positions=   47,400,150 positions/s=187,256
tiles= 26800/47743 positions=   47,584,282 positions/s=187,204
tiles= 26900/47743 positions=   47,749,910 positions/s=187,075
tiles= 27000/47743 positions=   47,937,256 positions/s=187,031
tiles= 27100/47743 positions=   48,120,244 positions/s=186,979
tiles= 27200/47743 positions=   48,303,734 positions/s=187,002
tiles= 27300/47743 positions=   48,481,420 positions/s=186,999
tiles= 27400/47743 positions=   48,674,066 positions/s=187,061
tiles= 27500/47743 positions=   48,846,748 positions/s=187,038
tiles= 27600/47743 positions=   49,022,762 positions/s=187,034
tiles= 27700/47743 positions=   49,196,900 positions/s=187,021
tiles= 27800/47743 positions=   49,366,402 positions/s=186,987
tiles= 27900/47743 positions=   49,542,946 positions/s=186,989
tiles= 28000/47743 positions=   49,714,988 positions/s=186,969
tiles= 28100/47743 positions=   49,876,310 positions/s=186,920
tiles= 28200/47743 positions=   50,034,104 positions/s=186,852
tiles= 28300/47743 positions=   50,212,314 positions/s=186,851
tiles= 28400/47743 positions=   50,396,244 positions/s=186,836
tiles= 28500/47743 positions=   50,580,182 positions/s=186,765
tiles= 28600/47743 positions=   50,749,842 positions/s=186,672
tiles= 28700/47743 positions=   50,933,260 positions/s=186,603
tiles= 28800/47743 positions=   51,114,402 positions/s=186,584
tiles= 28900/47743 positions=   51,282,720 positions/s=186,496
tiles= 29000/47743 positions=   51,463,140 positions/s=186,432
tiles= 29100/47743 positions=   51,633,318 positions/s=186,330
tiles= 29200/47743 positions=   51,786,952 positions/s=186,219
tiles= 29300/47743 positions=   51,950,142 positions/s=186,122
tiles= 29400/47743 positions=   52,131,694 positions/s=186,020
tiles= 29500/47743 positions=   52,307,740 positions/s=185,920
tiles= 29600/47743 positions=   52,484,774 positions/s=185,849
tiles= 29700/47743 positions=   52,667,742 positions/s=185,766
tiles= 29800/47743 positions=   52,836,878 positions/s=185,645
tiles= 29900/47743 positions=   53,014,976 positions/s=185,571
tiles= 30000/47743 positions=   53,186,290 positions/s=185,477
tiles= 30100/47743 positions=   53,346,730 positions/s=185,358
tiles= 30200/47743 positions=   53,520,628 positions/s=185,335
tiles= 30300/47743 positions=   53,701,622 positions/s=185,353
tiles= 30400/47743 positions=   53,877,370 positions/s=185,348
tiles= 30500/47743 positions=   54,046,088 positions/s=185,325
tiles= 30600/47743 positions=   54,223,940 positions/s=185,329
tiles= 30700/47743 positions=   54,400,730 positions/s=185,299
tiles= 30800/47743 positions=   54,575,258 positions/s=185,271
tiles= 30900/47743 positions=   54,757,562 positions/s=185,276
tiles= 31000/47743 positions=   54,934,358 positions/s=185,279
tiles= 31100/47743 positions=   55,106,042 positions/s=185,247
tiles= 31200/47743 positions=   55,279,538 positions/s=185,234
tiles= 31300/47743 positions=   55,461,288 positions/s=185,251
tiles= 31400/47743 positions=   55,623,260 positions/s=185,199
tiles= 31500/47743 positions=   55,779,762 positions/s=185,126
tiles= 31600/47743 positions=   55,943,812 positions/s=185,082

In [16]:
metric_rows = []
positive_cache = {}
hard_cache = {}

for segment, state in eval_states.items():
    positive_baseline_score = np.concatenate(
        state["positive_baseline_score"]
    )
    positive_rerank_score = np.concatenate(
        state["positive_rerank_score"]
    )
    positive_intensity = np.concatenate(
        state["positive_intensity"]
    )
    positive_count = np.concatenate(
        state["positive_count"]
    )

    hard_baseline = np.concatenate(
        state["hard_candidate_baseline_score"]
    )
    hard_rerank = np.concatenate(
        state["hard_candidate_rerank_score"]
    )

    keep = min(
        VALIDATION_HARD_FP_KEEP,
        len(hard_baseline),
    )

    if len(hard_baseline) > keep:
        idx = np.argpartition(
            hard_baseline,
            -keep,
        )[-keep:]

        hard_baseline = hard_baseline[idx]
        hard_rerank = hard_rerank[idx]

    baseline_ap = ap_from_histograms(
        state["baseline_positive_hist"],
        state["baseline_total_hist"],
    )
    reranker_ap = ap_from_histograms(
        state["rerank_positive_hist"],
        state["rerank_total_hist"],
    )

    metric_rows.append(
        {
            "segment": segment,
            "positive_n": int(len(positive_count)),
            "baseline_AP_5dp": baseline_ap,
            "reranker_AP_5dp": reranker_ap,
            "delta_AP": reranker_ap - baseline_ap,
            "baseline_presence_spearman_raw": dense_rank_pearson(
                positive_baseline_score,
                positive_count,
            ),
            "reranker_spearman_raw": dense_rank_pearson(
                positive_rerank_score,
                positive_count,
            ),
            "frozen_intensity_spearman_raw": dense_rank_pearson(
                positive_intensity,
                positive_count,
            ),
        }
    )

    positive_cache[segment] = {
        "baseline_score": positive_baseline_score,
        "rerank_score": positive_rerank_score,
        "count": positive_count,
    }

    hard_cache[segment] = {
        "baseline_score": hard_baseline,
        "rerank_score": hard_rerank,
    }

final_metrics = (
    pd.DataFrame(metric_rows)
    .sort_values("segment")
    .reset_index(drop=True)
)

FINAL_METRICS_PATH = RUN_DIR / "final_validation_metrics.csv"
final_metrics.to_csv(FINAL_METRICS_PATH, index=False)

display(final_metrics)
print("Saved:", FINAL_METRICS_PATH)

,segment,positive_n,baseline_AP_5dp,reranker_AP_5dp,delta_AP,baseline_presence_spearman_raw,reranker_spearman_raw,frozen_intensity_spearman_raw
0,NC_064034.1,23529,0.033783,0.007611,-0.026171,0.191207,0.106980,0.203072
1,NC_064041.1,13984,0.028973,0.007121,-0.021852,0.221014,0.145913,0.234122
2,NC_064042.1,18692,0.038690,0.010077,-0.028614,0.206500,0.115241,0.220363
3,overall,56205,0.033997,0.008222,-0.025775,0.177041,0.102931,0.188709

Saved: D:\Projects\EPIC\EPIC\artifacts\experiments\CNN_EXP037_FROZEN_WIDTH64_HARDFP_RERANKER\run_001\final_validation_metrics.csv

In [17]:
overall_state = eval_states["overall"]
overall_positive = positive_cache["overall"]
overall_hard = hard_cache["overall"]

baseline_positive_score = overall_positive["baseline_score"]
rerank_positive_score = overall_positive["rerank_score"]

low_tp_cutoff = float(
    np.quantile(
        baseline_positive_score,
        0.25,
    )
)
low_tp_mask = baseline_positive_score <= low_tp_cutoff

budget_rows = []

for fraction in BUDGETS:
    baseline_stats = budget_stats(
        overall_state["baseline_total_hist"],
        overall_state["baseline_positive_hist"],
        fraction,
    )
    rerank_stats = budget_stats(
        overall_state["rerank_total_hist"],
        overall_state["rerank_positive_hist"],
        fraction,
    )

    baseline_threshold = baseline_stats["threshold"]
    rerank_threshold = rerank_stats["threshold"]

    baseline_low_tp_recall = float(
        np.mean(
            baseline_positive_score[low_tp_mask]
            >= baseline_threshold
        )
    )
    rerank_low_tp_recall = float(
        np.mean(
            rerank_positive_score[low_tp_mask]
            >= rerank_threshold
        )
    )

    hard_remain_baseline = int(
        np.sum(
            overall_hard["baseline_score"]
            >= baseline_threshold
        )
    )
    hard_remain_rerank = int(
        np.sum(
            overall_hard["rerank_score"]
            >= rerank_threshold
        )
    )

    budget_rows.append(
        {
            "top_fraction": fraction,

            "baseline_actual_selected_fraction": (
                baseline_stats["selected_fraction"]
            ),
            "baseline_precision": baseline_stats["precision"],
            "baseline_recall": baseline_stats["recall"],
            "baseline_FP": baseline_stats["fp"],

            "reranker_actual_selected_fraction": (
                rerank_stats["selected_fraction"]
            ),
            "reranker_precision": rerank_stats["precision"],
            "reranker_recall": rerank_stats["recall"],
            "reranker_FP": rerank_stats["fp"],

            "baseline_hardFP_cohort_remaining": hard_remain_baseline,
            "reranker_hardFP_cohort_remaining": hard_remain_rerank,

            "baseline_LOW_TP_recall": baseline_low_tp_recall,
            "reranker_LOW_TP_recall": rerank_low_tp_recall,
            "delta_LOW_TP_recall": (
                rerank_low_tp_recall
                - baseline_low_tp_recall
            ),
        }
    )

budget_diagnostics = pd.DataFrame(budget_rows)

BUDGET_PATH = RUN_DIR / "top_budget_diagnostics.csv"
budget_diagnostics.to_csv(BUDGET_PATH, index=False)

display(budget_diagnostics)

print("Baseline LOW_TP cutoff:", low_tp_cutoff)
print("LOW_TP n:", int(low_tp_mask.sum()))
print("Saved:", BUDGET_PATH)

,top_fraction,baseline_actual_selected_fraction,baseline_precision,baseline_recall,baseline_FP,reranker_actual_selected_fraction,reranker_precision,reranker_recall,reranker_FP,baseline_hardFP_cohort_remaining,reranker_hardFP_cohort_remaining,baseline_LOW_TP_recall,reranker_LOW_TP_recall,delta_LOW_TP_recall
0,0.01,0.010000,0.022838,0.340539,818936,0.010001,0.012769,0.190410,827446,20000,9079,0.0,0.005124,0.005124
1,0.05,0.050002,0.008167,0.608914,4156320,0.050001,0.006105,0.455173,4164859,20000,16359,0.0,0.066539,0.066539
2,0.10,0.100002,0.004963,0.740041,8339283,0.100002,0.004173,0.622204,8345943,20000,18764,0.0,0.174281,0.174281

Baseline LOW_TP cutoff: 0.5802421569824219
LOW_TP n: 14052
Saved: D:\Projects\EPIC\EPIC\artifacts\experiments\CNN_EXP037_FROZEN_WIDTH64_HARDFP_RERANKER\run_001\top_budget_diagnostics.csv

## 6. Result JSON

Главный вопрос:

> превратился ли найденный 64-D TP/HARD_FP signal в реальный AP gain на естественном фоне?

In [18]:
WIDTH64_REFERENCE_AP = 0.03399689188641901

overall_row = (
    final_metrics[
        final_metrics["segment"] == "overall"
    ]
    .iloc[0]
)

contig_rows = final_metrics[
    final_metrics["segment"] != "overall"
]

improved_contigs = int(
    np.sum(contig_rows["delta_AP"] > 0)
)

summary = {
    "experiment": {
        "id": EXPERIMENT_ID,
        "architecture": (
            "frozen WIDTH64 RF1029 backbone + "
            "linear 64->1 presence reranker"
        ),
        "selected_config": BEST_CONFIG,
        "cv_selection_metric": (
            "mean natural-background AP on held-out train contigs"
        ),
        "low_tp_optimized": False,
    },
    "validation": {
        "reference_width64_AP": WIDTH64_REFERENCE_AP,
        "baseline_recomputed_AP": float(
            overall_row["baseline_AP_5dp"]
        ),
        "reranker_AP": float(
            overall_row["reranker_AP_5dp"]
        ),
        "delta_AP": float(
            overall_row["delta_AP"]
        ),
        "improved_validation_contigs": improved_contigs,
        "validation_contigs_total": int(len(contig_rows)),
        "baseline_presence_spearman_raw": float(
            overall_row["baseline_presence_spearman_raw"]
        ),
        "reranker_spearman_raw": float(
            overall_row["reranker_spearman_raw"]
        ),
        "frozen_intensity_spearman_raw": float(
            overall_row["frozen_intensity_spearman_raw"]
        ),
    },
    "files": {
        "train_feature_bank": str(FEATURE_BANK_PATH),
        "cross_contig_cv": str(CV_RESULTS_PATH),
        "cross_contig_cv_summary": str(CV_SUMMARY_PATH),
        "final_head": str(FINAL_HEAD_PATH),
        "final_validation_metrics": str(FINAL_METRICS_PATH),
        "top_budget_diagnostics": str(BUDGET_PATH),
    },
}

RESULT_JSON = RUN_DIR / "EXP037_RESULT.json"

RESULT_JSON.write_text(
    json.dumps(
        summary,
        ensure_ascii=False,
        indent=2,
        allow_nan=False,
    ),
    encoding="utf-8",
)

print("=" * 80)
print("EXP037 COMPLETE")
print("=" * 80)
print()
print(
    json.dumps(
        summary["validation"],
        ensure_ascii=False,
        indent=2,
    )
)
print()
print("Send me:")
print(RESULT_JSON)
print(BUDGET_PATH)
print(CV_SUMMARY_PATH)

================================================================================
EXP037 COMPLETE
================================================================================

{
  "reference_width64_AP": 0.03399689188641901,
  "baseline_recomputed_AP": 0.03399689188641901,
  "reranker_AP": 0.008222069686748124,
  "delta_AP": -0.025774822199670887,
  "improved_validation_contigs": 0,
  "validation_contigs_total": 3,
  "baseline_presence_spearman_raw": 0.17704136669635773,
  "reranker_spearman_raw": 0.10293099284172058,
  "frozen_intensity_spearman_raw": 0.18870866298675537
}

Send me:
D:\Projects\EPIC\EPIC\artifacts\experiments\CNN_EXP037_FROZEN_WIDTH64_HARDFP_RERANKER\run_001\EXP037_RESULT.json
D:\Projects\EPIC\EPIC\artifacts\experiments\CNN_EXP037_FROZEN_WIDTH64_HARDFP_RERANKER\run_001\top_budget_diagnostics.csv
D:\Projects\EPIC\EPIC\artifacts\experiments\CNN_EXP037_FROZEN_WIDTH64_HARDFP_RERANKER\run_001\cross_contig_cv_summary.csv

## 7. Optional registration

Compatibility-layer со старым experiment reporter уже встроен.

In [19]:
SAVE_EXPERIMENT = False

REPORT_METRICS_PATH = (
    RUN_DIR
    / "validation_metrics_report.csv"
)

report_metrics = (
    final_metrics[
        [
            "segment",
            "reranker_AP_5dp",
            "reranker_spearman_raw",
        ]
    ]
    .rename(
        columns={
            "reranker_AP_5dp": "average_precision",
            "reranker_spearman_raw": "epic_spearman",
        }
    )
)

report_metrics.to_csv(
    REPORT_METRICS_PATH,
    index=False,
)

CARD_PATH = (
    PROJECT_ROOT
    / "cnn_exp"
    / f"{EXPERIMENT_ID}.md"
)

CARD_PATH.parent.mkdir(
    parents=True,
    exist_ok=True,
)

if not CARD_PATH.exists():
    CARD_PATH.write_text(
        f'''---
id: {EXPERIMENT_ID}
type: experiment
experiment_type: cnn-candidate
status: completed
decision: review
date: 2026-09-24
seed: 42
split_version: contig_holdout_v1
primary_metric: average_precision
secondary_metric: epic_spearman
reference_experiment: CNN-EXP-036
tags:
  - ml/experiment
  - ml/cnn
  - ml/hard-negative
  - ml/ranking
---

# {EXPERIMENT_ID} — Frozen WIDTH64 Hard-FP Reranker

← [[cnn_exp/_index.md|Реестр CNN]]

## Pre-registration

- **Гипотеза:** hard-negative sampling + ranking objective улучшат
  natural-background AP при frozen WIDTH64 backbone.
- **Единственное изменение:** новая linear presence-head и objective/sampling.
- **Что заморожено:** WIDTH64 backbone, RF1029, split, sequence representation,
  old intensity-head.
- **Reference:** [[cnn_exp/CNN-EXP-036.md|CNN-EXP-036]].

## Автоматический отчёт

<!-- auto:cnn-experiment-report:start -->

<!-- auto:cnn-experiment-report:end -->

## Ручные заметки

-
''',
        encoding="utf-8",
    )

print("Reporter metrics:", REPORT_METRICS_PATH)
print("Card:", CARD_PATH)

Reporter metrics: D:\Projects\EPIC\EPIC\artifacts\experiments\CNN_EXP037_FROZEN_WIDTH64_HARDFP_RERANKER\run_001\validation_metrics_report.csv
Card: D:\Projects\EPIC\EPIC\cnn_exp\CNN-EXP-037.md

In [20]:
if SAVE_EXPERIMENT:
    from ml_project.cnn_experiment_report import (
        finalize_cnn_experiment,
    )

    reference_report_metrics = (
        EXP036_RUN
        / "validation_metrics_report.csv"
    )

    assert reference_report_metrics.is_file(), (
        "Нет EXP036 validation_metrics_report.csv. "
        "Сначала выполни compatibility adapter в EXP036."
    )

    finalization = finalize_cnn_experiment(
        project_root=PROJECT_ROOT,
        experiment_id=EXPERIMENT_ID,
        title="Frozen WIDTH64 Hard-FP Reranker",
        hypothesis=(
            "Hard-negative sampling plus pairwise ranking "
            "can improve natural-background AP using a "
            "frozen WIDTH64 representation."
        ),
        notebook_path=(
            "notebooks/experiments/CNN_experiments/"
            "CNN_EXP037_FROZEN_WIDTH64_HARDFP_RERANKER.ipynb"
        ),
        artifact_dir=RUN_DIR,
        training_history=(
            EXP036_RUN
            / "training_history.csv"
        ),
        candidate_metrics=REPORT_METRICS_PATH,
        reference_experiment="CNN-EXP-036",
        reference_metrics=reference_report_metrics,
        decision="review",
        notes=(
            "Frozen WIDTH64 backbone. Linear presence reranker. "
            "LOW_TP diagnostic only."
        ),
    )

    print("Obsidian:", finalization.card_path)
    print("Summary:", finalization.summary_path)
    print("Plots:", finalization.plot_dir)

else:
    print(
        "SAVE_EXPERIMENT=False. "
        "Сначала пришли EXP037_RESULT.json, "
        "top_budget_diagnostics.csv и "
        "cross_contig_cv_summary.csv."
    )

SAVE_EXPERIMENT=False. Сначала пришли EXP037_RESULT.json, top_budget_diagnostics.csv и cross_contig_cv_summary.csv.